/*
 * React Fabric
 * @version: 1.0.0
 *
 *
 * The MIT License (MIT)
 * Copyright (c) 2024 Adarsh Pastakia
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* istanbul ignore file */

export default {
  mime(mime: string = "") {
    const ret = (this.mimeList as KeyValue)[mime.split(";")[0]];
    if (!ret && !!mime) {
      const [t, e] = mime.split("/");
      return `${t} (${e})`;
    }
    return ret || "Unknown type";
  },
  mimeList: {
    "application/x-tika-msoffice": "Microsft Office File",
    "application/x-tika-ooxml": "Open Office File",
    "3d/vnd.adobe.dn+dcx": "Adobe Dimension",
    "application-x/geogebra-file": "Ggb",
    "application/acad": "DWG",
    "application/acrobat": "PDF Family",
    "application/applefile": "AppleSingle",
    "application/atom+xml": "Atom",
    "application/autocad_dwg": "DWG",
    "application/binhex": "BinHex",
    "application/bizagi-modeler": "BizAgi Process Modeler",
    "application/cbor": "Concise Binary Object Representation",
    "application/csv": "CSV",
    "application/dart": "Dart",
    "application/dbase": "MapInfo Data File (DAT)",
    "application/dbf": "MapInfo Data File (DAT)",
    "application/dec-dx.": "DEC Data Exchange File",
    "application/dicom": "DICOM",
    "application/dita+xml": "Darwin Information Typing Architecture",
    "application/dita+xml;format=concept": "DITA Concept Topic",
    "application/dita+xml;format=map": "DITA Map",
    "application/dita+xml;format=task": "DITA Task Topic",
    "application/dita+xml;format=topic": "DITA Topic",
    "application/dita+xml;format=val": "DITA Conditional Processing Profile",
    "application/dwf": "DWF",
    "application/dwg": "DWG",
    "application/dxf": "DXF",
    "application/ecmascript": "ActionScript",
    "application/epub+zip": "EBook",
    "application/f4m": "F4M",
    "application/fits": "Flexible Image Transport System",
    "application/font-tdpfr": "PFR",
    "application/font-woff": "WOFF",
    "application/freemind": "Mm",
    "application/futuresplash": "SWF",
    "application/gdiff": "GDIFF",
    "application/geopackage+sqlite3": "GeoPackage",
    "application/gml+xml": "Geo XML",
    "application/gzip": "Gzip Archive",
    "application/gzip-compressed": "Gzip Archive",
    "application/gzipped": "Gzip Archive",
    "application/iges": "IGES",
    "application/illustrator": "Adobe Illustrator",
    "application/inf": "INF (Windows)",
    "application/internet-shortcut": "Internet Shortcut",
    "application/java-applet": "Java Applet",
    "application/java-archive": "Java Archive",
    "application/java-serialized-object": "Java Serialized Object",
    "application/java-vm": "Java Class File",
    "application/javascript": "JavaScript",
    "application/jpg": "JFIF",
    "application/json": "JSON",
    "application/json-patch+json": "JSON Patch",
    "application/kate": "Kate",
    "application/ld+json": "JSON-LD",
    "application/mac-binhex": "BinHex",
    "application/mac-binhex40": "BinHex",
    "application/macbinary": "MacBinary",
    "application/marc": "MARC",
    "application/mbox": "Mbox",
    "application/msexcel": "Microsoft Excel Spreadsheet",
    "application/msonenote": "Microsoft OneNote",
    "application/mspowerpoint": "Microsoft Powerpoint Presentation",
    "application/msword": "Word Document",
    "application/msword2": "Microsoft Word 2 Document",
    "application/msword5": "Microsoft Word 5 Document",
    "application/mxf": "MXF",
    "application/netcdf": "NetCDF",
    "application/octet-stream": "Binary File",
    "application/ogg": "Ogg",
    "application/oxps": "OpenXPS",
    "application/package": "Package (Web)",
    "application/pdf": "PDF",
    "application/photoshop": "Photoshop Image",
    "application/pkcs10": "PKCS10",
    "application/playerpro": "Module Music Formats (Mods)",
    "application/postscript": "PostScript",
    "application/qif": "Quicken Interchange Format",
    "application/rdf+xml": "RDF",
    "application/rss+xml": "RSS",
    "application/rtf": "RTF",
    "application/sereal": "Sereal",
    "application/sgml": "SGML",
    "application/sla": "STereo Lithography",
    "application/sld": "AutoCAD Slide",
    "application/sldworks": "SolidWorks CAD program",
    "application/smil": "SMIL Multimedia",
    "application/smil+xml": "SMIL Multimedia",
    "application/soundapp": "Module Music Formats (Mods)",
    "application/ssml+xml": "Speech Synthesis Markup Language",
    "application/tif": "TIFF",
    "application/tiff": "TIFF",
    "application/typescript": "TypeScript",
    "application/vnd.adobe.adept+xml": "Adobe Content Server Message File",
    "application/vnd.adobe.flash-movie": "SWF",
    "application/vnd.adobe.folio+zip": "Folio",
    "application/vnd.adobe.indesign-idml-package": "IDML",
    "application/vnd.adobe.pdfxml": "PDF XML",
    "application/vnd.adobe.x-mars": "PDF XML",
    "application/vnd.adobe.xdp+xml": "XDP",
    "application/vnd.adobe.xfdf": "XFDF",
    "application/vnd.api+json": "JSON API",
    "application/vnd.apple.pkpass": "PKPass",
    "application/vnd.android.package-archive": "Android package",
    "application/vnd.chess-pgn": "PGN",
    "application/vnd.coffeescript": "CoffeeScript",
    "application/vnd.comicbook+zip": "Comic Book Archive",
    "application/vnd.comicbook-rar": "Comic Book Archive",
    "application/vnd.cups-raster": "CUPS Raster",
    "application/vnd.debian.binary-package": "Deb",
    "application/vnd.etsi.asic-e+zip":
      "Extended Associated Signature Container",
    "application/vnd.etsi.asic-s+zip": "Simple Associated Signature Container",
    "application/vnd.fdf": "FDF",
    "application/vnd.font-fontforge-sfd": "Spline Font Database",
    "application/vnd.framemaker": "FrameMaker",
    "application/vnd.geo+json": "GeoJSON",
    "application/vnd.geogebra.file": "Ggb",
    "application/vnd.gerber": "Gerber format",
    "application/vnd.google-earth.kml+xml": "KML",
    "application/vnd.google-earth.kmz": "KML",
    "application/vnd.hp-pcl": "PCL",
    "application/vnd.hp-pclxl": "PCL",
    "application/vnd.kde.kchart": "KChart File",
    "application/vnd.kde.kpresenter": "KPresenter File",
    "application/vnd.kde.kspread": "KSpread File",
    "application/vnd.kde.kword": "KWord File",
    "application/vnd.koan": "SSEYO Koan File",
    "application/vnd.las": "LAS (LASer) File Format",
    "application/vnd.lotus-1-2-3": "Lotus 1-2-3",
    "application/vnd.lotus-notes": "Notes Storage Facility",
    "application/vnd.lotus-wordpro": "Lotus Word Pro",
    "application/vnd.makemusic.notation": "Finale",
    "application/vnd.mif": "Maker Interchange Format",
    "application/vnd.mindjet.mindmanager": "MindManager",
    "application/vnd.ms-asf": "ASF",
    "application/vnd.ms-cab-compressed": "Cabinet",
    "application/vnd.ms-excel": "Excel Spreadsheet",
    "application/vnd.ms-excel.addin.macroenabled.12": "Microsoft Excel",
    "application/vnd.ms-excel.sheet.2": "Microsoft Excel 2 Worksheet",
    "application/vnd.ms-excel.sheet.3": "Microsoft Excel 3 Worksheet",
    "application/vnd.ms-excel.sheet.4": "Microsoft Excel 4 Worksheet",
    "application/vnd.ms-excel.sheet.binary.macroenabled.12": "Microsoft Excel",
    "application/vnd.ms-excel.sheet.macroenabled.12": "Microsoft Excel",
    "application/vnd.ms-excel.template.macroenabled.12": "Microsoft Excel",
    "application/vnd.ms-excel.workspace.3": "Microsoft Excel 3 Workspace",
    "application/vnd.ms-excel.workspace.4": "Microsoft Excel 4 Workspace",
    "application/vnd.ms-fontobject": "Embedded OpenType",
    "application/vnd.ms-htmlhelp": "CHM",
    "application/vnd.ms-officetheme": "Microsoft Office Theme",
    "application/vnd.ms-outlook": "Personal Folder File",
    "application/vnd.ms-outlook-pst": "Outlook Personal Folders File Format",
    "application/vnd.ms-package.3dmanufacturing-3dmodel+xml": "3MF",
    "application/vnd.ms-powerpoint": "Powerpoint Presentation",
    "application/vnd.ms-powerpoint.addin.macroenabled.12":
      "Microsoft PowerPoint",
    "application/vnd.ms-powerpoint.presentation.macroenabled.12":
      "Microsoft PowerPoint",
    "application/vnd.ms-powerpoint.slide.macroenabled.12":
      "Microsoft PowerPoint",
    "application/vnd.ms-powerpoint.slideshow.macroenabled.12":
      "Microsoft PowerPoint",
    "application/vnd.ms-powerpoint.template.macroenabled.12":
      "Microsoft PowerPoint",
    "application/vnd.ms-printing.printticket+xml": "3MF",
    "application/vnd.ms-tnef": "Transport Neutral Encapsulation Format",
    "application/vnd.ms-visio": "Microsoft Visio Diagram",
    "application/vnd.ms-visio.drawing":
      "Office Open XML Visio Drawing (macro-free)",
    "application/vnd.ms-visio.drawing.macroenabled.12":
      "Office Open XML Visio Drawing (macro-enabled)",
    "application/vnd.ms-visio.stencil":
      "Office Open XML Visio Stencil (macro-free)",
    "application/vnd.ms-visio.stencil.macroenabled.12":
      "Office Open XML Visio Stencil (macro-enabled)",
    "application/vnd.ms-visio.template":
      "Office Open XML Visio Template (macro-free)",
    "application/vnd.ms-visio.template.macroenabled.12":
      "Office Open XML Visio Template (macro-enabled)",
    "application/vnd.ms-word": "Word Document",
    "application/vnd.ms-word.document.macroenabled.12": "Microsoft Word",
    "application/vnd.ms-word.template.macroenabled.12": "Microsoft Word",
    "application/vnd.ms-xpsdocument": "OpenXPS",
    "application/vnd.nitf": "National Imagery Transmission Format",
    "application/vnd.oasis.opendocument.base": "OD",
    "application/vnd.oasis.opendocument.chart": "OD Chart",
    "application/vnd.oasis.opendocument.chart-template": "OD Chart Template",
    "application/vnd.oasis.opendocument.database": "OD Database",
    "application/vnd.oasis.opendocument.formula": "OD",
    "application/vnd.oasis.opendocument.formula-template": "OD Formula",
    "application/vnd.oasis.opendocument.graphics": "OD Graphics",
    "application/vnd.oasis.opendocument.graphics-template": "OD Graphics",
    "application/vnd.oasis.opendocument.image": "OD Image",
    "application/vnd.oasis.opendocument.image-template": "OD Image template",
    "application/vnd.oasis.opendocument.presentation": "OD Presentation",
    "application/vnd.oasis.opendocument.presentation-template":
      "OD Presentation Template",
    "application/vnd.oasis.opendocument.spreadsheet": "OD Spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template": "OD Spreadsheet",
    "application/vnd.oasis.opendocument.text": "OD Text",
    "application/vnd.oasis.opendocument.text-master": "OD Text",
    "application/vnd.oasis.opendocument.text-template": "OD Text Template",
    "application/vnd.oasis.opendocument.text-web": "OD Text",
    "application/vnd.openxmlformats-officedocument.presentationml.document":
      "OOXML Format Family -- ISO/IEC 29500 and ECMA 376",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation":
      "Powerpoint Presentation",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow":
      "Microsoft PowerPoint",
    "application/vnd.openxmlformats-officedocument.presentationml.template":
      "Microsoft PowerPoint",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.document":
      "OOXML Format Family -- ISO/IEC 29500 and ECMA 376",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
      "Excel Spreadsheet",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template":
      "Microsoft Excel",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
      "Word Document",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template":
      "Microsoft Word",
    "application/vnd.pagemaker": "Pagemaker Document (Generic)",
    "application/vnd.palm": "Palm OS Database",
    "application/vnd.pdf": "PDF Family",
    "application/vnd.quark.quarkxpress": "QuarkXPress",
    "application/vnd.rar": "RAR",
    "application/vnd.rn-realmedia": "RealMedia",
    "application/vnd.scribus": "Scribus",
    "application/vnd.sqlite3": "SQLite",
    "application/vnd.stardivision.calc": "SDC",
    "application/vnd.stardivision.chart": "StarOffice binary formats",
    "application/vnd.stardivision.draw": "StarOffice binary formats",
    "application/vnd.stardivision.impress": "StarOffice binary formats",
    "application/vnd.stardivision.impress-packed": "StarOffice binary formats",
    "application/vnd.stardivision.mail": "StarOffice binary formats",
    "application/vnd.stardivision.math": "StarOffice binary formats",
    "application/vnd.stardivision.writer": "SDW",
    "application/vnd.stardivision.writer-global": "StarOffice binary formats",
    "application/vnd.sun.xml.calc": "OpenOffice.org XML",
    "application/vnd.sun.xml.calc.template": "OpenOffice.org XML",
    "application/vnd.sun.xml.draw": "OpenOffice.org XML",
    "application/vnd.sun.xml.draw.template": "OpenOffice.org XML",
    "application/vnd.sun.xml.impress": "SXI",
    "application/vnd.sun.xml.impress.template": "SXI",
    "application/vnd.sun.xml.math": "OpenOffice.org XML",
    "application/vnd.sun.xml.writer": "SXW",
    "application/vnd.sun.xml.writer.global": "OpenOffice.org XML",
    "application/vnd.sun.xml.writer.template": "STW",
    "application/vnd.tcpdump.pcap": "TCPDump pcap packet capture",
    "application/vnd.truedoc": "PFR",
    "application/vnd.valve.source.material": "Valve Material Type",
    "application/vnd.visio": "Visio",
    "application/vnd.visio2013": "Visio VSDX Drawing File Format",
    "application/vnd.wap.wmlc": "Compiled WML Document",
    "application/vnd.wap.wmlscriptc": "Compiled WML Script",
    "application/vnd.wolfram.cdf": "Computable Document Format",
    "application/vnd.wolfram.cdf.text": "Computable Document Format",
    "application/vnd.wordperfect": "WordPerfect",
    "application/vnd.xara": "Xar (vector graphics)",
    "application/vnd.xmi+xml": "XML Metadata Interchange",
    "application/warc": "WARC",
    "application/warc-fields": "WARC",
    "application/x--iworks-protected": "Password Protected iWorks File",
    "application/x--msoffice-embedded;format=comp_obj":
      "CompObj OLE2 Embedded Document",
    "application/x--msoffice-embedded;format=ole10_native":
      "OLE10 Native Embedded Document",
    "application/x--old-excel": "Pre-OLE2 (Old) Microsoft Excel Worksheets",
    "application/x--ooxml-protected": "Password Protected OOXML File",
    "application/x--visio-ooxml": "Visio OOXML File",
    "application/x-3ds": "3DS",
    "application/x-3dxmlplugin": "3DXML",
    "application/x-7z-compressed": "7z Archive",
    "application/x-acad": "DWG",
    "application/x-adobe-indesign": "Adobe InDesign document",
    "application/x-adobe-indesign-interchange":
      "Adobe InDesign Interchange format",
    "application/x-apple-diskimage": "Apple Disk Image",
    "application/x-aspx": "ASP.NET",
    "application/x-astrotite-afa": "Astrotite",
    "application/x-autocad": "DWG",
    "application/x-axcrypt": "AxCrypt",
    "application/x-b6z-compressed": "B6Z",
    "application/x-berkeley-db": "Berkeley DB",
    "application/x-berkeley-db;format=btree": "Berkeley DB BTree Database",
    "application/x-berkeley-db;format=hash": "Berkeley DB Hash Database",
    "application/x-berkeley-db;format=log": "Berkeley DB Log Database",
    "application/x-berkeley-db;format=queue": "Berkeley DB Queue Database",
    "application/x-bittorrent": "Torrent file",
    "application/x-bplist": "Backup list",
    "application/x-bzip2": "Bzip2",
    "application/x-cbr": "Comic Book Archive",
    "application/x-cdf": "CD Audio",
    "application/x-cdlink": "Virtual CD-ROM CD Image File",
    "application/x-cfs-compressed": "Compact File Set",
    "application/x-chess-pgn": "PGN",
    "application/x-chrome-package": "Chrome Extension Package",
    "application/x-compress": "Compress (Unix)",
    "application/x-compressed": "Tape Archive",
    "application/x-cpio": "Cpio",
    "application/x-csv": "CSV",
    "application/x-dbase": "dBASE Table (DBF)",
    "application/x-dbf": "dBASE Table (DBF)",
    "application/x-dbm": "Berkeley DB",
    "application/x-debian-package": "Debian package",
    "application/x-deflate": "ZLIB Archive",
    "application/x-dex": "Dalvik Executable Format",
    "application/x-dgc-compressed": "DGCA",
    "application/x-director": "Shockwave (Director)",
    "application/x-dosexec": "DOS/Windows executable (EXE)",
    "application/x-dvi": "DVI (Device Independent File Format)",
    "application/x-dwg": "DWG",
    "application/x-elc": "Emacs Lisp bytecode",
    "application/x-emf": "Extended Metafile",
    "application/x-endnote-connect": "EndNote Connection File",
    "application/x-endnote-connection": "EndNote Connection File",
    "application/x-endnote-refer": "EndNote Import File",
    "application/x-endnote-style": "EndNote Style File",
    "application/x-erb": "HTML+ERB",
    "application/x-fictionbook+xml": "FictionBook document",
    "application/x-filemaker": "FileMaker Pro 7",
    "application/x-font-adobe-metric": "Adobe Font Metric",
    "application/x-font-otf": "OpenType Font",
    "application/x-font-printer-metric": "Printer Font Metric",
    "application/x-font-ttf": "TrueType Font",
    "application/x-foxmail": "Foxmail Email File",
    "application/x-frame": "FrameMaker Interchange Format",
    "application/x-freemind": "Mm",
    "application/x-futuresplash": "Macromedia FutureSplash File",
    "application/x-gca-compressed": "GCA",
    "application/x-glulx": "Glulx",
    "application/x-gnumeric": "Gnumeric",
    "application/x-grib":
      "General Regularly-distributed Information in Binary form",
    "application/x-gtar": "GNU Archive",
    "application/x-gunzip": "Gzip Compressed Archive",
    "application/x-gzip": "Gzip",
    "application/x-gzip-compressed": "Gzip Compressed Archive",
    "application/x-hdf": "HDF",
    "application/x-httpd-jsp": "Java Server Page",
    "application/x-httpd-php": "HTML+PHP",
    "application/x-hwp": "Hangul Word Processor File",
    "application/x-hwp-v5": "Hangul Word Processor File v5",
    "application/x-ibooks+zip": "Apple iBooks",
    "application/x-isatab": "ISA-Tab Study file",
    "application/x-isatab-assay": "ISA-Tab Assay file",
    "application/x-isatab-investigation": "ISA-Tab Investigation file",
    "application/x-iso9660-image": "ISO image",
    "application/x-itunes-ipa": "Apple iOS IPA AppStore file",
    "application/x-java": "Java Class File",
    "application/x-java-jnilib": "Java Native Library for OSX",
    "application/x-java-jnlp-file": "Java Network Launching Protocol",
    "application/x-java-vm": "Java Class File",
    "application/x-javascript": "JavaScript Source Code",
    "application/x-jpg": "JFIF",
    "application/x-jsp": "Groovy Server Pages",
    "application/x-kchart": "KChart File",
    "application/x-killustrator": "KIllustrator File",
    "application/x-koan": "SSEYO Koan File",
    "application/x-kpresenter": "KPresenter File",
    "application/x-krita": "Krita",
    "application/x-kspread": "KSpread File",
    "application/x-kword": "KWord File",
    "application/x-latex": "LaTeX Source Document",
    "application/x-lotus-notes": "Notes Storage Facility",
    "application/x-lzh-compressed": "LHA",
    "application/x-lzip": "Lzip",
    "application/x-lzma": "LZMA Alone",
    "application/x-macbinary": "MacBinary",
    "application/x-maff": "MAFF",
    "application/x-matlab-data": "MAT",
    "application/x-matroska": "Matroska Media",
    "application/x-midi": "MIDI",
    "application/x-mif": "FrameMaker Interchange Format",
    "application/x-mplayer2": "ASF (Advanced Systems Format)",
    "application/x-msaccess": "Microsoft Access",
    "application/x-msdownload": "Microsoft Download",
    "application/x-ms-installer": "Microsoft Windows Installer",
    "application/x-ms-wim": "Windows Imaging Format",
    "application/x-msi": "Microsoft Windows Installer",
    "application/x-msmetafile": "Windows Metafile",
    "application/x-mso": "ActiveMime",
    "application/x-mysql-misam-compressed-index":
      "MySQL MISAM Compressed Index",
    "application/x-mysql-misam-data": "MySQL MISAM Data",
    "application/x-mysql-misam-index": "MySQL MISAM Index",
    "application/x-mysql-table-definition": "MySQL Table Definition (Format)",
    "application/x-navi-animation": "Windows Animated Cursor",
    "application/x-pdf": "Portable Document Format",
    "application/x-pn-mpg": "MPEG-2 Video Encoding (H.262)",
    "application/x-powershell": "PowerShell",
    "application/x-rar": "RAR archive",
    "application/x-rar-compressed": "RAR",
    "application/x-riff": "MIDI Instrument Definition File",
    "application/x-roxio-toast": "TOAST",
    "application/x-rpm": "RedHat Package Manager",
    "application/x-sas": "SAS Program",
    "application/x-sas-access": "SAS Access Descriptor",
    "application/x-sas-audit": "SAS Audit",
    "application/x-sas-backup": "SAS Backup",
    "application/x-sas-catalog": "SAS Catalog",
    "application/x-sas-data": "SAS Data Set",
    "application/x-sas-data-index": "SAS Data Set Index",
    "application/x-sas-dmdb": "SAS DMDB Data Mining Database File",
    "application/x-sas-fdb": "SAS FDB Consolidation Database File",
    "application/x-sas-itemstor": "SAS Item Store (ItemStor) File",
    "application/x-sas-mddb": "SAS MDDB Multi-Dimensional Database File",
    "application/x-sas-program-data": "SAS Stored Program (DATA Step)",
    "application/x-sas-putility": "SAS Permanent Utility",
    "application/x-sas-transport": "SAS Transport File",
    "application/x-sas-utility": "SAS Utility",
    "application/x-sas-view": "SAS Data Set View",
    "application/x-sas-xport": "SAS Transport (XPORT) Family",
    "application/x-setupscript": "Windows setup INFormation",
    "application/x-sh": "UNIX/LINUX Shell Script",
    "application/x-shockwave-flash": "SWF",
    "application/x-shockwave-flash2-preview": "Macromedia Flash",
    "application/x-silverlight-app": "Silverlight",
    "application/x-sit": "StuffIt",
    "application/x-sitx": "StuffIt X",
    "application/x-sld": "AutoCAD Slide",
    "application/x-snappy-framed": "Snappy",
    "application/x-speex": "Speex Audio",
    "application/x-spss-por": "SPSS Portable File",
    "application/x-spss-sav": "SAV",
    "application/x-sqlite3": "SQLite",
    "application/x-starcalc": "SDC",
    "application/x-stardraw": "SDA (StarOffice)",
    "application/x-starwriter": "SDW",
    "application/x-stuffit": "StuffIt",
    "application/x-stuffitx": "StuffIt X",
    "application/x-t3vm-image": "TADS 3",
    "application/x-tads": "TADS",
    "application/x-tar": "Tape Archive",
    "application/x-tcl": "Tcl script",
    "application/x-tex": "TeX",
    "application/x-tif": "TIFF",
    "application/x-tiff": "TIFF",
    "application/x-troff":
      "Roff/nroff/troff/groff Unformatted Manual Page (UNIX)",
    "application/x-troff-man":
      "Roff/nroff/troff/groff Unformatted Manual Page (UNIX)",
    "application/x-troff-me":
      "Roff/nroff/troff/groff Unformatted Manual Page (UNIX)",
    "application/x-troff-ms":
      "Roff/nroff/troff/groff Unformatted Manual Page (UNIX)",
    "application/x-troff-msvideo": "AVI (Audio Video Interleaved) File Format",
    "application/x-url": "Internet Shortcut",
    "application/x-vhd": "Virtual PC Virtual Hard Disk",
    "application/x-vmdk": "Virtual Disk Format",
    "application/x-vnd.corel.designer.document+zip": "Corel Designer",
    "application/x-vnd.corel.zcf.designer.document+zip": "Corel Designer",
    "application/x-vnd.oasis.opendocument.chart": "OD Chart",
    "application/x-vnd.oasis.opendocument.chart-template": "OD Chart Template",
    "application/x-vnd.oasis.opendocument.formula": "OD Formula document",
    "application/x-vnd.oasis.opendocument.formula-template":
      "OD Formula Template",
    "application/x-vnd.oasis.opendocument.graphics": "OD Graphics (Drawing)",
    "application/x-vnd.oasis.opendocument.graphics-template":
      "OD Graphics Template",
    "application/x-vnd.oasis.opendocument.image": "OD Image",
    "application/x-vnd.oasis.opendocument.image-template": "OD Image Template",
    "application/x-vnd.oasis.opendocument.presentation": "OD Presentation",
    "application/x-vnd.oasis.opendocument.presentation-template":
      "OD Presentation Template",
    "application/x-vnd.oasis.opendocument.spreadsheet": "OD Spreadsheet",
    "application/x-vnd.oasis.opendocument.spreadsheet-template":
      "OD Spreadsheet Template",
    "application/x-vnd.oasis.opendocument.text": "OD Text",
    "application/x-vnd.oasis.opendocument.text-master": "OD Global Text",
    "application/x-vnd.oasis.opendocument.text-template": "OD Text Template",
    "application/x-vnd.oasis.opendocument.text-web": "OD Text Template",
    "application/x-vnd.sun.xml.writer": "OpenOffice v1.0: Writer Document",
    "application/x-votable+xml": "VOTable",
    "application/x-web-app-manifest+json": "Open Web App Manifest",
    "application/x-windows-installer": "Microsoft Windows Installer",
    "application/x-wine-extension-inf": "Windows setup INFormation",
    "application/x-www-form-urlencoded": "Form URL encoding",
    "application/x-x509-ca-cert": "DER encoded certificate",
    "application/x-x509-user-cert": "DER encoded certificate",
    "application/x-xmind": "XMind Pro",
    "application/x-xml": "Extensible Markup Language",
    "application/x-xpinstall": "Cross-Platform Installer Module",
    "application/x-xz": "XZ",
    "application/x-zip-compressed": "Zip Archive",
    "application/x-zoo": "Zoo",
    "application/xhtml+xml": "HTML",
    "application/xml": "XML",
    "application/xml-dtd": "DTD",
    "application/xquery": "XQuery source code",
    "application/xslfo+xml": "XSL Format",
    "application/xslt+xml": "XSL Transformations",
    "application/xspf+xml": "XML Shareable Playlist Format",
    "application/zip": "Zip Archive",
    "application/zlib": "ZLIB Compressed Data Format",
    "application/zstd": "Zstandard",
    "audio/3gpp": "3GP Audio",
    "audio/3gpp2": "3G2 Audio",
    "audio/8svx": "8-Bit Sampled Voice Audio",
    "audio/aiff": "AIFF Audio",
    "audio/amr": "Adaptive Multi-Rate Audio",
    "audio/application/x-pn-realmedia": "RealMedia Audio",
    "audio/asf": "ASF Audio",
    "audio/aud": "WeChat Audio",
    "audio/audible": "Audible.Com Audio",
    "audio/avi": "AVI Audio",
    "audio/basic": "AU Audio",
    "audio/flac": "FLAC Audio",
    "audio/it": "Module Music Formats (Mods) Audio",
    "audio/m": "MIDI Audio",
    "audio/med": "Module Music Formats (Mods) Audio",
    "audio/mid": "MIDI Audio",
    "audio/midi": "MIDI Audio",
    "audio/mod": "Module Music Formats (Mods) Audio",
    "audio/module-xm": "Module Music Formats (Mods) Audio",
    "audio/mp3": "MP3 Audio",
    "audio/mp4": "MP4 Audio",
    "audio/mp4a-latm": "MP4 Audio",
    "audio/mpa": "MPEG Audio Layer I Audio",
    "audio/mpeg": "MP3 Audio",
    "audio/mpeg3": "MP3 Audio",
    "audio/mpg": "MP3 Audio",
    "audio/ogg": "Ogg Multimedia File Audio",
    "audio/ogg; codecs=speex": "Speex Audio Codec Audio",
    "audio/opus": "Opus Audio",
    "audio/prs.sid": "SID Audio",
    "audio/rmf": "AIFF Audio",
    "audio/s3m": "Module Music Formats (Mods) Audio",
    "audio/speex": "Speex Audio",
    "audio/vnd.qcelp": "AIFF Audio",
    "audio/vnd.rn-realaudio": "RealAudio",
    "audio/vnd.wave": "WAV Audio",
    "audio/vorbis": "Vorbis Audio",
    "audio/wav": "WAV Audio",
    "audio/wave": "WAV Audio",
    "audio/webm": "WebM Audio",
    "audio/x-8svx": "8-Bit Sampled Voice Audio",
    "audio/x-aiff": "AIFF Audio",
    "audio/x-amr-wb": "Adaptive Multi-Rate WideBand Audio",
    "audio/x-flac": "FLAC Audio",
    "audio/x-gsm": "AIFF Audio",
    "audio/x-matroska": "Matroska Audio",
    "audio/x-midi": "MIDI Audio",
    "audio/x-mod": "EPSGMOD Audio",
    "audio/x-mp3": "MP3 Audio",
    "audio/x-mpeg": "MPEG-1 Audio Layer 3 Audio",
    "audio/x-mpeg3": "MP3 Audio",
    "audio/x-mpegaudio": "MP3 Audio",
    "audio/x-mpegurl": "MP3 Playlist File Audio",
    "audio/x-mpg": "MP3 Audio",
    "audio/x-ms-wax": "Windows Media Metafile Audio",
    "audio/x-ogg": "Ogg Audio",
    "audio/x-ogg-flac": "Free Lossless Audio",
    "audio/x-ogg-pcm": "Unompressed Audio",
    "audio/x-oggflac": "Free Lossless Audio",
    "audio/x-oggpcm": "Unompressed Audio",
    "audio/x-pn-aiff": "AIFF Audio",
    "audio/x-pn-audibleaudio": "Audible.Com Audio",
    "audio/x-pn-realaudio": "RealAudio",
    "audio/x-pn-realaudio-plugin": "RAM (RealAudio) Audio",
    "audio/x-pn-wav": "WAV Audio",
    "audio/x-realaudio": "Real Audio",
    "audio/x-rmf": "AIFF Audio",
    "audio/x-s3m": "Module Music Formats (Mods) Audio",
    "audio/x-speex": "Speex Audio Codec Audio",
    "audio/x-voc": "Creative Voice File Audio",
    "audio/x-wav": "WAV Audio",
    "audio/x-xm": "Module Music Formats (Mods) Audio",
    "audio/xm": "Extended Module Audio File Audio",
    "chemical/x-cif": "CIF",
    "chemical/x-cml": "CML",
    "chemical/x-mdl-molfile": "MOL",
    "chemical/x-pdb": "Brookhaven Protein Databank File",
    "drawing/dwg": "DWG",
    "gzip/document": "Gzip Compressed Archive",
    "image/ascii-art": "ASCII Art",
    "image/avi": "AVI (Audio Video Interleaved) File Format",
    "image/avif": "AVIF",
    "image/avif-sequence": "AVIF",
    "image/bmp": "BMP",
    "image/cgm": "CGM",
    "image/cis-cod": "Lightning Strike",
    "image/dicom-rle": "DICOM",
    "image/emf": "Enhanced Metafile",
    "image/fits": "Flexible Image Transport System",
    "image/flif": "Free Lossless Image Format (FLIF)",
    "image/g3fax": "CCITT Group 3",
    "image/gif": "GIF",
    "image/heic": "HEIC",
    "image/heic-sequence": "High Efficiency Image File Format",
    "image/heif": "HEIF",
    "image/image/x-ptx": "Pentax PEF",
    "image/ivg": "IconVG",
    "image/jls": "JPEG-LS",
    "image/jp2": "JP2",
    "image/jpeg": "JPEG",
    "image/jpeg2000": "JPEG 2000 Part 1 (Core) jp2 File Format",
    "image/jpeg2000-image": "JPEG 2000 Part 1 (Core) jp2 File Format",
    "image/jpg": "JFIF",
    "image/jpm": "JPM",
    "image/jpx": "JPX",
    "image/jxl": "JPEG XL",
    "image/jxr": "JPEG Extended Range",
    "image/ktx": "KTX",
    "image/mov": "QuickTime File Format",
    "image/naplps": "NAPLPS",
    "image/nia": "Naïve Image Formats",
    "image/nie": "Naïve Image Formats",
    "image/nii": "Naïve Image Formats",
    "image/openraster": "OpenRaster",
    "image/pict": "PICT",
    "image/png": "PNG",
    "image/png+json": "Piskel canvas",
    "image/pwg-raster": "PWG Raster",
    "image/svg+xml": "Scalable Vector Graphics",
    "image/svg-xml": "Scalable Vector Graphics",
    "image/tif": "TIFF",
    "image/tiff": "TIFF",
    "image/tiff-fx": "TIFF-FX",
    "image/vnd-wap-wbmp": "Wireless Bitmap",
    "image/vnd.adobe.photoshop": "PSD",
    "image/vnd.djvu": "DjVu",
    "image/vnd.dwg": "DWG",
    "image/vnd.dxb": "AutoCAD DXF simplified Binary",
    "image/vnd.dxf": "DXF",
    "image/vnd.dxf;format=ascii": "AutoCAD DXF in ASCII Text form",
    "image/vnd.dxf;format=binary": "AutoCAD DXF in Binary form",
    "image/vnd.fpx": "FlashPix",
    "image/vnd.fujixerox.edmics-mmr": "Xerox EDMICS-MMR",
    "image/vnd.fujixerox.edmics-rlc": "Xerox EDMICS-RLC",
    "image/vnd.microsoft.icon": "ICO",
    "image/vnd.mix": "MIX (Picture It!)",
    "image/vnd.mozilla.apng": "APNG",
    "image/vnd.ms-modi": "MDI",
    "image/vnd.ms-photo": "JPEG XR",
    "image/vnd.radiance": "Radiance HDR",
    "image/vnd.rn-realflash": "Macromedia Flash SWF File Format",
    "image/vnd.svf": "Simple Vector Format",
    "image/vnd.tencent.tap": "TAP (Tencent)",
    "image/vnd.valve.source.texture": "Valve Texture Format",
    "image/vnd.wap.wbmp": "WBMP",
    "image/vnd.xiff": "XIFF",
    "image/vnd.zbrush.pcx": "PCX",
    "image/vpb": "Quantel VPB image",
    "image/webp": "Web Photo",
    "image/wmf": "Windows Metafile",
    "image/x-3ds": "3DS",
    "image/x-bmp": "Bitmap Image File (BMP)",
    "image/x-bpg": "Better Portable Graphics",
    "image/x-canon-cr3": "Canon RAW 3",
    "image/x-canon-crw": "Camera Image File Format",
    "image/x-dcx": "Multipage Zsoft Paintbrush Bitmap Graphics",
    "image/x-djvu": "DjVu File Format",
    "image/x-dpx": "Digital Moving-Picture Exchange (DPX)",
    "image/x-dwg": "DWG",
    "image/x-freehand": "FreeHand image",
    "image/x-hasselblad-3fr": "Hasselblad 3FR",
    "image/x-icon": "ICO",
    "image/x-jng": "JPEG Network Graphics",
    "image/x-jp2-codestream": "JPEG 2000 Codestream",
    "image/x-jp2-container": "JPEG 2000 Container Format",
    "image/x-jpeg2000-image": "JPEG 2000 Part 1 (Core) jp2 File Format",
    "image/x-mrsid": "MrSID",
    "image/x-mrsid-image": "MrSID Image Format",
    "image/x-ms-bmp": "Windows bitmap",
    "image/x-niff": "Navy Interchange File Format",
    "image/x-pcx": "PCX",
    "image/x-pentax-pef": "Pentax PEF",
    "image/x-pict": "PICT",
    "image/x-portable-anymap": "Netpbm formats",
    "image/x-portable-arbitrarymap": "Portable Arbitrary Map",
    "image/x-portable-bitmap": "Netpbm formats",
    "image/x-portable-graymap": "Netpbm formats",
    "image/x-portable-pixmap": "Netpbm formats",
    "image/x-psd": "Photoshop Image",
    "image/x-quicktime": "QuickTime File Format",
    "image/x-raw-adobe": "Adobe Digital Negative",
    "image/x-raw-canon": "Canon raw image",
    "image/x-raw-casio": "Casio raw image",
    "image/x-raw-epson": "Epson raw image",
    "image/x-raw-fuji": "Fuji raw image",
    "image/x-raw-hasselblad": "Hasselblad raw image",
    "image/x-raw-imacon": "Imacon raw image",
    "image/x-raw-kodak": "Kodak raw image",
    "image/x-raw-leaf": "Leaf raw image",
    "image/x-raw-logitech": "Logitech raw image",
    "image/x-raw-mamiya": "Mamiya raw image",
    "image/x-raw-minolta": "Minolta raw image",
    "image/x-raw-nikon": "Nikon raw image",
    "image/x-raw-olympus": "Olympus raw image",
    "image/x-raw-panasonic": "Panasonic raw image",
    "image/x-raw-pentax": "Pentax raw image",
    "image/x-raw-phaseone": "Phase One raw image",
    "image/x-raw-rawzor": "Rawzor raw image",
    "image/x-raw-red": "Red raw image",
    "image/x-raw-sigma": "Sigma raw image",
    "image/x-raw-sony": "Sony raw image",
    "image/x-rgb": "Silicon Graphics RGB Bitmap",
    "image/x-sgi-bw": "Silicon Graphics Image",
    "image/x-sld": "AutoCAD Slide",
    "image/x-sun-raster": "Sun Raster Image",
    "image/x-tif": "TIFF",
    "image/x-tiff": "TIFF",
    "image/x-win-bitmap": "Microsoft Windows Cursor",
    "image/x-wmf": "Windows Metafile",
    "image/x-xbitmap": "XBM",
    "image/x-xcf": "GIMP Image File",
    "image/x-xwindowdump": "X Windows Dump",
    "image/xcf": "GIMP Image File",
    "interface/x-winamp-skin": "Winamp Skin",
    "message/rfc822": "Internet e-mail message format",
    "model/gltf+json": "glTF (GL Transmission Format) 2.0",
    "model/gltf-binary": "glTF (GL Transmission Format) 2.0",
    "model/iges": "IGES",
    "model/mtl": "Wavefront Material Template Library (MTL) File Format",
    "model/obj": "Wavefront OBJ File Format",
    "model/prc": "Product Representation Compact (PRC) File Format",
    "model/stl": "STL (STereoLithography) File Format",
    "model/u3d": "Universal 3D (U3D) format family. ECMA-363",
    "model/vnd-dwf": "DWF",
    "model/vnd.adobe.dn+dcxucf": "Adobe Dimension",
    "model/vnd.collada+xml": "COLLADA",
    "model/vnd.dwfx+xps": "AutoCAD Design Web Format",
    "model/vnd.usdz+zip": "USDZ",
    "model/vnd.valve.source.compiled-map": "BSP",
    "model/vrml": "VRML",
    "model/x3d+binary": "X3D",
    "model/x3d+fastinfoset": "Extensible 3D",
    "model/x3d+vrml": "X3D",
    "model/x3d+xml": "X3D",
    "model/x3d-vrml": "Extensible 3D",
    "multipart/appledouble": "AppleDouble",
    "multipart/x-tar": "Tape Archive",
    "sound/aiff": "AIFF",
    "text/apl": "APL",
    "text/asp": "Active Server Page",
    "text/aspdotnet": "ASP .NET",
    "text/calendar": "ICalendar",
    "text/comma-separated-values": "CSV",
    "text/css": "Cascading Style Sheets",
    "text/csv": "CSV",
    "text/csv-schema": "CSV Schema",
    "text/dns": "Zone file",
    "text/ecmascript": "ECMA Script",
    "text/gemini": "Gemini",
    "text/html": "HTML",
    "text/javascript": "JavaScript",
    "text/json": "JSON (JavaScript Object Notation)",
    "text/jsx": "TSX",
    "text/markdown": "Markdown",
    "text/mirc": "IRC log",
    "text/n3": "Notation3",
    "text/pdf": "PDF Family",
    "text/plain": "Plain text",
    "text/properties": "Java Properties",
    "text/rtf": "RTF",
    "text/sgml": "SGML",
    "text/tab-separated-values": "Tab delimited",
    "text/troff": "Roff/nroff/troff/groff Unformatted Manual Page (UNIX)",
    "text/turtle": "Turtle",
    "text/url": "Internet Shortcut",
    "text/vbscript": "VBScript",
    "text/vcard": "VCard",
    "text/vnd.ascii-art": "ASCII Art",
    "text/vnd.iptc.anpa":
      "American Newspaper Publishers Association Wire Feeds",
    "text/vnd.iptc.nitf": "News Industry Text Format",
    "text/vnd.wap.wmlscript": "WML Script",
    "text/vtt": "WebVTT",
    "text/x-actionscript": "ActionScript source code",
    "text/x-ada": "Ada source code",
    "text/x-applescript": "AppleScript source code",
    "text/x-ascii-art": "ASCII Art",
    "text/x-asciidoc": "Asciidoc source code",
    "text/x-asm": "Assembler source code",
    "text/x-aspectj": "AspectJ source code",
    "text/x-assembly": "Assembler source code",
    "text/x-awk": "AWK script",
    "text/x-basic": "Basic source code",
    "text/x-brainfuck": "Brainfuck",
    "text/x-c": "C source code",
    "text/x-c++": "C++ source code",
    "text/x-c++hdr": "C++ source code header",
    "text/x-c++src": "C++ source code",
    "text/x-cgi": "CGI script",
    "text/x-chdr": "C source code header",
    "text/x-clojure": "Clojure source code",
    "text/x-cmake": "Makefile",
    "text/x-cobol": "COBOL source code",
    "text/x-coffeescript": "CoffeeScript source code",
    "text/x-coldfusion": "ColdFusion source code",
    "text/x-comma-separated-values": "CSV",
    "text/x-common-lisp": "Common Lisp source code",
    "text/x-cross-domain-policy": "Adobe Cross Domain Policy File",
    "text/x-crystal": "Crystal",
    "text/x-csharp": "C# source code",
    "text/x-csrc": "C source code",
    "text/x-csv": "CSV",
    "text/x-cython": "Cython",
    "text/x-d": "D source code",
    "text/x-diff": "Diff file",
    "text/x-django": "Jinja",
    "text/x-dockerfile": "Dockerfile",
    "text/x-dtd": "XML Document Type Definition",
    "text/x-dylan": "Dylan",
    "text/x-ebnf": "Lark",
    "text/x-ecl": "ECL",
    "text/x-eiffel": "Eiffel source code",
    "text/x-elm": "Elm",
    "text/x-emacs-lisp": "Emacs Lisp source code",
    "text/x-erlang": "Erlang source code",
    "text/x-expect": "Expect Script",
    "text/x-factor": "Factor",
    "text/x-forth": "Forth source code",
    "text/x-fortran": "Fortran source code",
    "text/x-fsharp": "F#",
    "text/x-gfm": "Markdown",
    "text/x-go": "Go source code",
    "text/x-groovy": "Groovy source code",
    "text/x-haml": "HAML source code",
    "text/x-haskell": "Haskell source code",
    "text/x-haxe": "Haxe source code",
    "text/x-idl": "Inteface Definition Language",
    "text/x-ini": "Configuration file",
    "text/x-java": "Java source code",
    "text/x-java-properties": "Java Properties",
    "text/x-java-source": "Java source code",
    "text/x-jsp": "Java Server Page",
    "text/x-julia": "Julia",
    "text/x-kotlin": "Kotlin",
    "text/x-less": "LESS source code",
    "text/x-lex": "Lex/Flex source code",
    "text/x-literate-haskell": "Literate Haskell",
    "text/x-livescript": "LiveScript",
    "text/x-log": "Log file",
    "text/x-lua": "Lua source code",
    "text/x-markdown": "Markdown",
    "text/x-mathematica": "Mathematica",
    "text/x-matlab": "Matlab source code",
    "text/x-ml": "ML source code",
    "text/x-modula": "Modula source code",
    "text/x-mumps": "M",
    "text/x-nfo": "NFO",
    "text/x-nginx-conf": "Nginx",
    "text/x-nh": "Newick tree Format",
    "text/x-nsis": "NSIS",
    "text/x-objcsrc": "Objective-C",
    "text/x-objectivec": "Objective-C++",
    "text/x-ocaml": "Ocaml source code",
    "text/x-octave": "MATLAB",
    "text/x-oz": "Oz",
    "text/x-pascal": "Pascal source code",
    "text/x-pdf": "PDF Family",
    "text/x-perl": "Perl script",
    "text/x-php": "PHP script",
    "text/x-plsql": "PLSQL",
    "text/x-prolog": "Prolog source code",
    "text/x-properties": "Java Properties",
    "text/x-protobuf": "Protocol Buffer",
    "text/x-pug": "Pug",
    "text/x-puppet": "Puppet",
    "text/x-python": "Python script",
    "text/x-rexx": "Rexx source code",
    "text/x-rpm-spec": "RPM Spec",
    "text/x-rsrc": "R",
    "text/x-rst": "reStructuredText source code",
    "text/x-ruby": "Ruby source code",
    "text/x-rustsrc": "ReScript",
    "text/x-sas": "SAS",
    "text/x-sass": "Sass",
    "text/x-scala": "Scala source code",
    "text/x-scheme": "Scheme source code",
    "text/x-scss": "SCSS",
    "text/x-sed": "Sed code",
    "text/x-server-parsed-html": "Server Side Includes",
    "text/x-server-parsed-html3": "Server Side Includes",
    "text/x-sh": "Shell",
    "text/x-slim": "Slim",
    "text/x-smarty": "Smarty",
    "text/x-soy": "Closure Templates",
    "text/x-spreadsheet": "LTspice Symbol",
    "text/x-sql": "SQL code",
    "text/x-stex": "BibTeX",
    "text/x-stsrc": "Smalltalk source code",
    "text/x-swift": "Swift",
    "text/x-systemverilog": "SystemVerilog",
    "text/x-tcl": "Tcl script",
    "text/x-tex": "TeX Source",
    "text/x-toml": "TOML",
    "text/x-ttcn-asn": "ASN.1",
    "text/x-twig": "Twig",
    "text/x-url": "Internet Shortcut",
    "text/x-vb": "Visual Basic .NET",
    "text/x-vbasic": "Visual basic source code",
    "text/x-vbdotnet": "VB.NET source code",
    "text/x-vbscript": "VBScript source code",
    "text/x-verilog": "Verilog source code",
    "text/x-vhdl": "VHDL source code",
    "text/x-web-markdown": "Markdown source code",
    "text/x-webidl": "WebIDL",
    "text/x-yacc": "Yacc/Bison source code",
    "text/x-yaml": "YAML source code",
    "text/xml": "XML",
    "text/xsl": "XSL Format",
    "video/3gpp": "3GP Video",
    "video/3gpp2": "3G2 Video",
    "video/avi": "AVI Video",
    "video/daala": "Ogg Daala Video",
    "video/jpm": "JPEG 2000 Part 6 (JPM) Video",
    "video/mj2": "MJ2 Video",
    "video/mp1s": "MPEG-2 Video",
    "video/mp2p": "MPEG-2 Video",
    "video/mp4": "MP4 Video",
    "video/mpeg": "MPEG-1 Video",
    "video/mpeg2": "MPEG-2 Video",
    "video/mpg": "MPEG-2 Video",
    "video/msvideo": "AVI Video",
    "video/ogg": "Ogg Video",
    "video/quicktime": "QuickTime Video",
    "video/theora": "Ogg Theora Video",
    "video/vnd-vivo": "VivoActive Video",
    "video/vnd.avi": "AVI Video",
    "video/vnd.radgamettools.bink": "Bink Video",
    "video/vnd.radgamettools.smacker": "Smacker Video",
    "video/vnd.rn-realvideo": "Real Video",
    "video/webm": "Web Movie",
    "video/x-daala": "Ogg Daala Video",
    "video/x-dirac": "Dirac Video",
    "video/x-dv": "DV-DIF Video",
    "video/x-flv": "FLV Video",
    "video/x-matroska": "Matroska Video",
    "video/x-matroska-3d": "Matroska Video",
    "video/x-mng": "MNG Video",
    "video/x-mpeg": "MPEG-2 Video",
    "video/x-mpeg2a": "MPEG-2 Video",
    "video/x-mpg": "MPEG-2 Video",
    "video/x-ms-asf": "ASF Video",
    "video/x-ms-asf-plugin": "ASF Video",
    "video/x-ms-asx": "Windows Media Metafile Video",
    "video/x-ms-wm": "ASF Video",
    "video/x-ms-wma": "WMA Video",
    "video/x-ms-wmv": "WMV Video",
    "video/x-msvideo": "AVI Video",
    "video/x-ogg-rgb": "Raw RGB Video",
    "video/x-ogg-uvs": "Raw UVS Video",
    "video/x-ogg-yuv": "Raw YUV Video",
    "video/x-oggrgb": "Raw RGB Video",
    "video/x-ogguvs": "Raw UVS Video",
    "video/x-oggyuv": "Raw YUV Video",
    "video/x-ogm": "OGM Video",
    "video/x-quicktime": "QuickTime Video",
    "video/x-sgi-movie": "SGI movie Video",
    "video/x-theora": "Ogg Theora Video",
    "wwwserver/redirection": "Internet Shortcut",
    "x-conference/x-cooltalk": "Cooltalk Audio",
    "x-world/x-3dmf": "3DMF",
  },
};
