import Color from "color";

const sorter = (a, b) => {
  const cola = Color(a.color);
  const colb = Color(b.color);
  if (Math.round(cola.hue() / 30) === Math.round(colb.hue() / 30)) {
    if (Math.round(cola.l() / 10) === Math.round(colb.l() / 10)) {
      return cola.b() > colb.b() ? -1 : 1;
    }
    return cola.l() < colb.l() ? -1 : 1;
  }
  return cola.hue() < colb.hue() ? -1 : 1;
};

export const CopToner = [
  { color: "#ECEDED", name: "Toner Gray No.0" },
  { color: "#EAEAE8", name: "Toner Gray No.1" },
  { color: "#E0E0DE", name: "Toner Gray No.2" },
  { color: "#D1D2CC", name: "Toner Gray No.3" },
  { color: "#BCBBB9", name: "Toner Gray No.4" },
  { color: "#A8A7A3", name: "Toner Gray No.5" },
  { color: "#949590", name: "Toner Gray No.6" },
  { color: "#777674", name: "Toner Gray No.7" },
  { color: "#63655F", name: "Toner Gray No.8" },
  { color: "#4C4B49", name: "Toner Gray No.9" },
  { color: "#322E2D", name: "Toner Gray No.10" },
];
export const CopNeutral = [
  { color: "#ECEEED", name: "Neutral Gray No.0" },
  { color: "#E2E3E5", name: "Neutral Gray No.1" },
  { color: "#DADBDD", name: "Neutral Gray No.2" },
  { color: "#D1D2D4", name: "Neutral Gray No.3" },
  { color: "#BCBDC1", name: "Neutral Gray No.4" },
  { color: "#A8A9AD", name: "Neutral Gray No.5" },
  { color: "#949599", name: "Neutral Gray No.6" },
  { color: "#77787C", name: "Neutral Gray No.7" },
  { color: "#636466", name: "Neutral Gray No.8" },
  { color: "#4C4D4F", name: "Neutral Gray No.9" },
  { color: "#312F30", name: "Neutral Gray No.10" },
];
export const CopCool = [
  { color: "#E0E7ED", name: "Cool Gray No.0" },
  { color: "#DAE3E8", name: "Cool Gray No.1" },
  { color: "#CCD7DD", name: "Cool Gray No.2" },
  { color: "#C1CCD2", name: "Cool Gray No.3" },
  { color: "#b7c1c8", name: "Cool Gray No.4" },
  { color: "#92A0AB", name: "Cool Gray No.5" },
  { color: "#88979e", name: "Cool Gray No.6" },
  { color: "#637079", name: "Cool Gray No.7" },
  { color: "#535D66", name: "Cool Gray No.8" },
  { color: "#3C474D", name: "Cool Gray No.9" },
  { color: "#202B31", name: "Cool Gray No.10" },
];
export const CopWarm = [
  { color: "#ECECE4", name: "Warm Gray No.0" },
  { color: "#E7E7DF", name: "Warm Gray No.1" },
  { color: "#DDDDD5", name: "Warm Gray No.2" },
  { color: "#D2D2CA", name: "Warm Gray No.3" },
  { color: "#BCBDB7", name: "Warm Gray No.4" },
  { color: "#A8A9A4", name: "Warm Gray No.5" },
  { color: "#94958F", name: "Warm Gray No.6" },
  { color: "#777873", name: "Warm Gray No.7" },
  { color: "#63645F", name: "Warm Gray No.8" },
  { color: "#4C4D48", name: "Warm Gray No.9" },
  { color: "#302F2B", name: "Warm Gray No.10" },
];

export const Crayola = [
  { color: "#ED0A3F", name: "Red" },
  { color: "#C32148", name: "Maroon" },
  { color: "#FD0E35", name: "Scarlet" },
  { color: "#C62D42", name: "Brick Red" },
  { color: "#CC474B", name: "English Vermilion" },
  { color: "#CC3336", name: "Madder Lake" },
  { color: "#E12C2C", name: "Permanent Geranium Lake" },
  { color: "#D92121", name: "Maximum Red" },
  { color: "#B94E48", name: "Indian Red" },
  { color: "#FF5349", name: "Orange-Red" },
  { color: "#FE4C40", name: "Sunset Orange" },
  { color: "#FE6F5E", name: "Bittersweet" },
  { color: "#B33B24", name: "Dark Venetian Red" },
  { color: "#CC553D", name: "Venetian Red" },
  { color: "#FF681F", name: "Red-Orange" },
  { color: "#E6735C", name: "Light Venetian Red" },
  { color: "#E77200", name: "Mango Tango" },
  { color: "#FF8833", name: "Orange" },
  { color: "#FF7F49", name: "Burnt Orange" },
  { color: "#FF9980", name: "Vivid Tangerine" },
  { color: "#E58E73", name: "Middle Red" },
  { color: "#FFB97B", name: "Macaroni and Cheese" },
  { color: "#ECB176", name: "Middle Yellow Red" },
  { color: "#FFAE42", name: "Yellow-Orange" },
  { color: "#F2BA49", name: "Maximum Yellow Red" },
  { color: "#FBE7B2", name: "Banana Mania" },
  { color: "#F2C649", name: "Maize" },
  { color: "#F8D568", name: "Orange-Yellow" },
  { color: "#FCD667", name: "Goldenrod" },
  { color: "#FED85D", name: "Dandelion" },
  { color: "#FBE870", name: "Yellow" },
  { color: "#F1E788", name: "Green-Yellow" },
  { color: "#FFEB00", name: "Middle Yellow" },
  { color: "#B5B35C", name: "Olive Green" },
  { color: "#ECEBBD", name: "Spring Green" },
  { color: "#FAFA37", name: "Maximum Yellow" },
  { color: "#FFFF99", name: "Canary" },
  { color: "#FFFF9F", name: "Lemon Yellow" },
  { color: "#D9E650", name: "Maximum Green Yellow" },
  { color: "#ACBF60", name: "Middle Green Yellow" },
  { color: "#AFE313", name: "Inchworm" },
  { color: "#BEE64B", name: "Light Chrome Green" },
  { color: "#C5E17A", name: "Yellow-Green" },
  { color: "#9DE093", name: "Granny Smith Apple" },
  { color: "#5E8C31", name: "Maximum Green" },
  { color: "#7BA05B", name: "Asparagus" },
  { color: "#4D8C57", name: "Middle Green" },
  { color: "#63B76C", name: "Fern" },
  { color: "#3AA655", name: "Green" },
  { color: "#6CA67C", name: "Medium Chrome Green" },
  { color: "#5FA777", name: "Forest Green" },
  { color: "#93DFB8", name: "Sea Green" },
  { color: "#33CC99", name: "Shamrock" },
  { color: "#1AB385", name: "Mountain Meadow" },
  { color: "#29AB87", name: "Jungle Green" },
  { color: "#00CC99", name: "Caribbean Green" },
  { color: "#00755E", name: "Tropical Rain Forest" },
  { color: "#01786F", name: "Pine Green" },
  { color: "#008080", name: "Teal Blue" },
  { color: "#30BFBF", name: "Maximum Blue Green" },
  { color: "#00CCCC", name: "Robin's Egg Blue" },
  { color: "#8DD9CC", name: "Middle Blue Green" },
  { color: "#8FD8D8", name: "Light Blue" },
  { color: "#95E0E8", name: "Aquamarine" },
  { color: "#6CDAE7", name: "Turquoise Blue" },
  { color: "#76D7EA", name: "Sky Blue" },
  { color: "#7ED4E6", name: "Middle Blue" },
  { color: "#0095B7", name: "Blue-Green" },
  { color: "#009DC4", name: "Pacific Blue" },
  { color: "#02A4D3", name: "Cerulean" },
  { color: "#47ABCC", name: "Maximum Blue" },
  { color: "#4997D0", name: "Blue (I)" },
  { color: "#339ACC", name: "Cerulean Blue" },
  { color: "#93CCEA", name: "Cornflower" },
  { color: "#2887C8", name: "Green-Blue" },
  { color: "#00468C", name: "Midnight Blue" },
  { color: "#0066CC", name: "Navy Blue" },
  { color: "#1560BD", name: "Denim" },
  { color: "#0066FF", name: "Blue (III)" },
  { color: "#A9B2C3", name: "Cadet Blue" },
  { color: "#C3CDE6", name: "Periwinkle" },
  { color: "#4570E6", name: "Blue (II)" },
  { color: "#7A89B8", name: "Wild Blue Yonder" },
  { color: "#4F69C6", name: "Indigo" },
  { color: "#8D90A1", name: "Manatee" },
  { color: "#8C90C8", name: "Cobalt Blue" },
  { color: "#7070CC", name: "Celestial Blue" },
  { color: "#9999CC", name: "Blue Bell" },
  { color: "#ACACE6", name: "Maximum Blue Purple" },
  { color: "#766EC8", name: "Violet-Blue" },
  { color: "#6456B7", name: "Blue-Violet" },
  { color: "#3F26BF", name: "Ultramarine Blue" },
  { color: "#8B72BE", name: "Middle Blue Purple" },
  { color: "#652DC1", name: "Purple Heart" },
  { color: "#6B3FA0", name: "Royal Purple" },
  { color: "#8359A3", name: "Violet (II)" },
  { color: "#8F47B3", name: "Medium Violet" },
  { color: "#C9A0DC", name: "Wisteria" },
  { color: "#BF8FCC", name: "Lavender (I)" },
  { color: "#803790", name: "Vivid Violet" },
  { color: "#733380", name: "Maximum Purple" },
  { color: "#D6AEDD", name: "Purple Mountains' Majesty" },
  { color: "#C154C1", name: "Fuchsia" },
  { color: "#FC74FD", name: "Pink Flamingo" },
  { color: "#732E6C", name: "Violet (I)" },
  { color: "#E667CE", name: "Brilliant Rose" },
  { color: "#E29CD2", name: "Orchid" },
  { color: "#8E3179", name: "Plum" },
  { color: "#D96CBE", name: "Medium Rose" },
  { color: "#EBB0D7", name: "Thistle" },
  { color: "#C8509B", name: "Mulberry" },
  { color: "#BB3385", name: "Red-Violet" },
  { color: "#D982B5", name: "Middle Purple" },
  { color: "#A63A79", name: "Maximum Red Purple" },
  { color: "#A50B5E", name: "Jazzberry Jam" },
  { color: "#614051", name: "Eggplant" },
  { color: "#F653A6", name: "Magenta" },
  { color: "#DA3287", name: "Cerise" },
  { color: "#FF3399", name: "Wild Strawberry" },
  { color: "#FBAED2", name: "Lavender (II)" },
  { color: "#FFB7D5", name: "Cotton Candy" },
  { color: "#FFA6C9", name: "Carnation Pink" },
  { color: "#F7468A", name: "Violet-Red" },
  { color: "#E30B5C", name: "Razzmatazz" },
  { color: "#FDD7E4", name: "Pig Pink" },
  { color: "#E62E6B", name: "Carmine" },
  { color: "#DB5079", name: "Blush" },
  { color: "#FC80A5", name: "Tickle Me Pink" },
  { color: "#F091A9", name: "Mauvelous" },
  { color: "#FF91A4", name: "Salmon" },
  { color: "#A55353", name: "Middle Red Purple" },
  { color: "#CA3435", name: "Mahogany" },
  { color: "#FEBAAD", name: "Melon" },
  { color: "#F7A38E", name: "Pink Sherbert" },
  { color: "#E97451", name: "Burnt Sienna" },
  { color: "#AF593E", name: "Brown" },
  { color: "#9E5B40", name: "Sepia" },
  { color: "#87421F", name: "Fuzzy Wuzzy" },
  { color: "#926F5B", name: "Beaver" },
  { color: "#DEA681", name: "Tumbleweed" },
  { color: "#D27D46", name: "Raw Sienna" },
  { color: "#664228", name: "Van Dyke Brown" },
  { color: "#D99A6C", name: "Tan" },
  { color: "#EDC9AF", name: "Desert Sand" },
  { color: "#FFCBA4", name: "Peach" },
  { color: "#805533", name: "Burnt Umber" },
  { color: "#FDD5B1", name: "Apricot" },
  { color: "#EED9C4", name: "Almond" },
  { color: "#665233", name: "Raw Umber" },
  { color: "#837050", name: "Shadow" },
  { color: "#E6BC5C", name: "Raw Sienna (I)" },
  { color: "#D9D6CF", name: "Timberwolf" },
  { color: "#92926E", name: "Gold (I)" },
  { color: "#E6BE8A", name: "Gold (II)" },
  { color: "#C9C0BB", name: "Silver" },
  { color: "#DA8A67", name: "Copper" },
  { color: "#C88A65", name: "Antique Brass" },
  { color: "#000000", name: "Black" },
  { color: "#2D383A", name: "Outer Space" },
  { color: "#736A62", name: "Charcoal Gray" },
  { color: "#8B8680", name: "Gray" },
  { color: "#C8C8CD", name: "Blue-Gray" },
  { color: "#FF355E", name: "Radical Red" },
  { color: "#FD5B78", name: "Wild Watermelon" },
  { color: "#FF6037", name: "Outrageous Orange" },
  { color: "#FF9966", name: "Atomic Tangerine" },
  { color: "#FF9933", name: "Neon Carrot" },
  { color: "#FFCC33", name: "Sunglow" },
  { color: "#FFFF66", name: "Laser Lemon" },
  { color: "#CCFF00", name: "Electric Lime" },
  { color: "#66FF66", name: "Screamin' Green" },
  { color: "#AAF0D1", name: "Magic Mint" },
  { color: "#50BFE6", name: "Blizzard Blue" },
  { color: "#FF6EFF", name: "Shocking Pink" },
  { color: "#EE34D2", name: "Razzle Dazzle Rose" },
  { color: "#FF00CC", name: "Hot Magenta" },
  { color: "#FF3855", name: "Sizzling Red" },
  { color: "#FD3A4A", name: "Red Salsa" },
  { color: "#FB4D46", name: "Tart Orange" },
  { color: "#FA5B3D", name: "Orange Soda" },
  { color: "#FFAA1D", name: "Bright Yellow" },
  { color: "#FFF700", name: "Yellow Sunshine" },
  { color: "#299617", name: "Slimy Green" },
  { color: "#A7F432", name: "Green Lizard" },
  { color: "#2243B6", name: "Denim Blue" },
  { color: "#5DADEC", name: "Blue Jeans" },
  { color: "#5946B2", name: "Plump Purple" },
  { color: "#9C51B6", name: "Purple Plum" },
  { color: "#A83731", name: "Sweet Brown" },
  { color: "#AF6E4D", name: "Brown Sugar" },
  { color: "#1B1B1B", name: "Eerie Black" },
  { color: "#BFAFB2", name: "Black Shadows" },
  { color: "#FF5470", name: "Fiery Rose" },
  { color: "#FFDB00", name: "Sizzling Sunrise" },
  { color: "#FF7A00", name: "Heat Wave" },
  { color: "#FDFF00", name: "Lemon Glacier" },
  { color: "#87FF2A", name: "Spring Frost" },
  { color: "#0048BA", name: "Absolute Zero" },
  { color: "#FF007C", name: "Winter Sky" },
  { color: "#E936A7", name: "Frostbite" },
].sort(sorter);

export const Copic = [
  { color: "#FFFFFF", name: "White" },
  { color: "#312B2B", name: "Black" },
  { color: "#030708", name: "Special Black" },
  { color: "#DDF0F4", name: "Frost Blue" },
  { color: "#E6F4F5", name: "Pale Porcelain Blue" },
  { color: "#F0F9FE", name: "Pale Celestine" },
  { color: "#D6EEF2", name: "Mint Blue" },
  { color: "#B3E3F1", name: "Robin's Egg Blue" },
  { color: "#73CFE6", name: "Tahitian Blue" },
  { color: "#40C5E6", name: "Process Blue" },
  { color: "#00B3E6", name: "Peacock Blue" },
  { color: "#C8E6F0", name: "Ice Blue" },
  { color: "#71CFEB", name: "Light Blue" },
  { color: "#00BCEA", name: "Cyanine Blue" },
  { color: "#1D8ACB", name: "Lapis Lazuli" },
  { color: "#DBEDF9", name: "Baby Blue" },
  { color: "#92C2E8", name: "Phthalo Blue" },
  { color: "#8ACEF3", name: "Sky" },
  { color: "#65B3E3", name: "Cobalt Blue" },
  { color: "#196DB6", name: "Royal Blue" },
  { color: "#0177C1", name: "Ultramarine" },
  { color: "#E2EFF7", name: "Pale Blue" },
  { color: "#82C3ED", name: "Manganese Blue" },
  { color: "#156FA4", name: "Antwerp Blue" },
  { color: "#2B64A9", name: "Prussian Blue" },
  { color: "#E2F0FB", name: "Powder Blue" },
  { color: "#75C0EA", name: "Smoky Blue" },
  { color: "#ADCDDC", name: "Soft Greenish Blue" },
  { color: "#DAE1F3", name: "Pale Blue Gray" },
  { color: "#A7BBE0", name: "Light Hydrangea" },
  { color: "#6888C5", name: "Clematis" },
  { color: "#2165AE", name: "Stratospheric Blue" },
  { color: "#3B479D", name: "Iris" },
  { color: "#D5E2EB", name: "Pale Grayish Blue" },
  { color: "#95C1DA", name: "Light Crockery Blue" },
  { color: "#60C5CF", name: "Light Grayish Cobalt" },
  { color: "#457A9A", name: "Night Blue" },
  { color: "#0F547E", name: "Agate" },
  { color: "#E5F4ED", name: "Pale Aqua" },
  { color: "#EFF8F3", name: "Snow Green" },
  { color: "#C7E6FA", name: "Aqua Blue" },
  { color: "#C6E8EA", name: "New Blue" },
  { color: "#1DB8CE", name: "Petroleum Blue" },
  { color: "#DCF0EF", name: "Blue Green" },
  { color: "#CEEBF1", name: "Moon White" },
  { color: "#C4E7E9", name: "Mint Green" },
  { color: "#A0D9D2", name: "Aqua" },
  { color: "#37C0B0", name: "Teal Blue" },
  { color: "#BDE5DD", name: "Coral Sea" },
  { color: "#BCE2D7", name: "Aqua Mint" },
  { color: "#A3DAD7", name: "Horizon Green" },
  { color: "#AFDFDF", name: "Nile Blue" },
  { color: "#00B6B9", name: "Duck Blue" },
  { color: "#ACCFD1", name: "Ice Mint" },
  { color: "#64BEBE", name: "Jasper" },
  { color: "#DAECEE", name: "Ocean Mist" },
  { color: "#74B8BB", name: "Ice Ocean" },
  { color: "#59918E", name: "Abyss Green" },
  { color: "#49706B", name: "Bronze" },
  { color: "#BAC1B9", name: "Green Gray" },
  { color: "#81A291", name: "Bush" },
  { color: "#6E9B87", name: "Flagstone Blue" },
  { color: "#E0DCED", name: "Mauve Shadow" },
  { color: "#C4C9E6", name: "Viola" },
  { color: "#AAB8DB", name: "Prune" },
  { color: "#7C97CE", name: "Blue Berry" },
  { color: "#EAE7F2", name: "Blue Violet" },
  { color: "#D4D2E8", name: "Soft Violet" },
  { color: "#8491C8", name: "Hydrangea Blue" },
  { color: "#6E84BD", name: "Deep Reddish Blue" },
  { color: "#CFDBF1", name: "Dull Lavender" },
  { color: "#B1C0DD", name: "Grayish Lavender" },
  { color: "#8184A7", name: "Grayish Violet" },
  { color: "#384558", name: "Slate" },
  { color: "#9FA7BC", name: "Bluebell" },
  { color: "#FDF3EA", name: "Skin White" },
  { color: "#FEF5EE", name: "Pale Fruit Pink" },
  { color: "#FFFAF4", name: "Floral White" },
  { color: "#FFEEE4", name: "Pink Flamingo" },
  { color: "#FEECE0", name: "Fruit Pink" },
  { color: "#E4BCC4", name: "Lipstick Natural" },
  { color: "#CC816A", name: "Light Mahogany" },
  { color: "#CA6553", name: "Brown" },
  { color: "#D96A4F", name: "Burnt Sienna" },
  { color: "#FEE9D6", name: "Bareley Beige" },
  { color: "#E9C5AF", name: "Light Suntan" },
  { color: "#FBBB8D", name: "Dark Suntan" },
  { color: "#B85F57", name: "Reddish Brass" },
  { color: "#88534D", name: "Copper" },
  { color: "#C45238", name: "Redwood" },
  { color: "#FDE2C7", name: "Baby Skin Pink" },
  { color: "#ECCAB1", name: "Hazelnut" },
  { color: "#D2A482", name: "Caribe Cocoa" },
  { color: "#997663", name: "Africano" },
  { color: "#884636", name: "Burnt Umber" },
  { color: "#F7F0D6", name: "Bisque" },
  { color: "#F2E6CE", name: "Brick Beige" },
  { color: "#F3D2B1", name: "Sand" },
  { color: "#F0CAA6", name: "Orientale" },
  { color: "#E6C3A3", name: "Chamois" },
  { color: "#CC9159", name: "Sepia" },
  { color: "#C5743F", name: "Leather" },
  { color: "#F2E8DC", name: "Brick White" },
  { color: "#FEF1E1", name: "Pearl White" },
  { color: "#F3EAD9", name: "Sand White" },
  { color: "#E8DABD", name: "Dull Ivory" },
  { color: "#8A6E59", name: "Clay" },
  { color: "#634C3C", name: "Dark Bark" },
  { color: "#F4EBF0", name: "Egg Shell" },
  { color: "#FEECD6", name: "Milky White" },
  { color: "#F1DFB9", name: "Raw Silk" },
  { color: "#B18558", name: "Light Walnut" },
  { color: "#9A7F6C", name: "Walnut" },
  { color: "#EFEAE6", name: "Ash Rose" },
  { color: "#A1847C", name: "Champagne" },
  { color: "#7F604E", name: "Maroon" },
  { color: "#4A2C22", name: "Cashew" },
  { color: "#F0E6C2", name: "Ivory" },
  { color: "#AE9F80", name: "Khaki" },
  { color: "#6F604D", name: "Fig" },
  { color: "#5A4939", name: "Pecan" },
  { color: "#FED2B9", name: "Tea Rose" },
  { color: "#FCBC7E", name: "Flesh Pink" },
  { color: "#B46034", name: "Deep Orange" },
  { color: "#F5A3C7", name: "Fluorescent Pink" },
  { color: "#7F74B6", name: "Fluorescent Dull Violet" },
  { color: "#FFF697", name: "Fluorescent Yellow Orange" },
  { color: "#FECC99", name: "Fluorescent Orange" },
  { color: "#EAF5ED", name: "Pale Green" },
  { color: "#F1F7F3", name: "Crystal Opal" },
  { color: "#CFE8D3", name: "Spectrum Green" },
  { color: "#B6DA9C", name: "Meadow Green" },
  { color: "#69C07B", name: "Emerald Green" },
  { color: "#7BC576", name: "Nile Green" },
  { color: "#7AC465", name: "Veronese Green" },
  { color: "#D2E8C4", name: "Sea Green" },
  { color: "#97CF90", name: "Apple Green" },
  { color: "#60C198", name: "Malachite" },
  { color: "#14B37D", name: "Forest Green" },
  { color: "#2DB98A", name: "Bright Parrot Green" },
  { color: "#EDF6DB", name: "Wax White" },
  { color: "#C4E4CD", name: "Lime Green" },
  { color: "#C3E0B4", name: "Willow" },
  { color: "#119462", name: "Ocean Green" },
  { color: "#197C5D", name: "Pine Tree Green" },
  { color: "#E4F1DF", name: "Dim Green" },
  { color: "#D7E7A8", name: "Pistachio" },
  { color: "#579e80", name: "Mistletoe" },
  { color: "#CCDAB9", name: "Spring Dim Green" },
  { color: "#9DC3AA", name: "Verdigris" },
  { color: "#98A786", name: "Grayish Olive" },
  { color: "#5F7E3A", name: "Olive" },
  { color: "#FEEAE1", name: "Pinkish White" },
  { color: "#FEF0E7", name: "Cherry White" },
  { color: "#FEF3EF", name: "Pink Beryl" },
  { color: "#FDE0D8", name: "Pinkish Vanilla" },
  { color: "#FDD3C7", name: "Flesh" },
  { color: "#F6917B", name: "Salmon Red" },
  { color: "#F26754", name: "Vermilion" },
  { color: "#FDE1D5", name: "Pale Cherry Pink" },
  { color: "#FCD3C1", name: "Light Tea Rose" },
  { color: "#F59B92", name: "Light Rouse" },
  { color: "#F4846C", name: "Lipstick Orange" },
  { color: "#FCD7CF", name: "Blush" },
  { color: "#FAC1B6", name: "Sardonyx" },
  { color: "#F8B7B1", name: "Light Prawn" },
  { color: "#F27579", name: "Prawn" },
  { color: "#F15062", name: "Cadmium Red" },
  { color: "#ED174B", name: "Lipstick Red" },
  { color: "#FCE3DF", name: "Pale Yellowish Pink" },
  { color: "#FAC1BA", name: "Peach" },
  { color: "#F27185", name: "Coral" },
  { color: "#E86C74", name: "Carmine" },
  { color: "#CB487A", name: "Garnet" },
  { color: "#EE848E", name: "Bougainvillaea" },
  { color: "#E04D69", name: "Strong Red" },
  { color: "#D27C95", name: "Currant" },
  { color: "#B74F70", name: "Cardinal" },
  { color: "#F1C8D6", name: "Rose Pink" },
  { color: "#F19CB9", name: "Rose Mist" },
  { color: "#D36A93", name: "Rose Red" },
  { color: "#7D2B42", name: "Dark Red" },
  { color: "#F1DAEA", name: "Water Lily" },
  { color: "#F4E2EE", name: "Pale Purple" },
  { color: "#F2EAF5", name: "Evening Primrose" },
  { color: "#FAD5E6", name: "Sugared Almond Pink" },
  { color: "#F6A3BF", name: "Shock Pink" },
  { color: "#F386AF", name: "Cerise" },
  { color: "#FDECF4", name: "Pale Pink" },
  { color: "#FBD6DD", name: "Pink" },
  { color: "#F9C9D7", name: "Tender Pink" },
  { color: "#F495B7", name: "Begonia Pink" },
  { color: "#DB7EB3", name: "Deep Magenta" },
  { color: "#D268AA", name: "Red Violet" },
  { color: "#FDE8E7", name: "Light Pink" },
  { color: "#F8BAC9", name: "Pure Pink" },
  { color: "#F493BE", name: "Dog Rose Flower" },
  { color: "#EF4880", name: "Crimson" },
  { color: "#FAD3CE", name: "Shadow Pink" },
  { color: "#F9AFAE", name: "Dark Pink" },
  { color: "#F8BBB6", name: "Salmon Pink" },
  { color: "#F9CADE", name: "Cotton Candy" },
  { color: "#E9A5CA", name: "Hollyhock" },
  { color: "#D09DAE", name: "Begonia" },
  { color: "#B86A84", name: "Raspberry" },
  { color: "#8B576E", name: "Peony" },
  { color: "#B684A1", name: "Baby Blossoms" },
  { color: "#5A4858", name: "Argyle Purple" },
  { color: "#E9E5F3", name: "Pale Heath" },
  { color: "#F0EDF6", name: "Rose Quartz" },
  { color: "#E4C1D9", name: "Heath" },
  { color: "#E6AACE", name: "Lilac" },
  { color: "#E2A6CA", name: "Marigold" },
  { color: "#CE95C2", name: "Lavender" },
  { color: "#8754A1", name: "Violet" },
  { color: "#EED7E9", name: "Pale Lilac" },
  { color: "#D3A6CD", name: "Mallow" },
  { color: "#A092C7", name: "Amethyst" },
  { color: "#E2E0ED", name: "Wisteria" },
  { color: "#B2B1D0", name: "Ash Lavender" },
  { color: "#857FAD", name: "Pale Blackberry" },
  { color: "#6B668E", name: "Eggplant" },
  { color: "#E8C4D0", name: "Pale Grape" },
  { color: "#E5C1DB", name: "Early Grape" },
  { color: "#B77CA8", name: "Light Grape" },
  { color: "#524358", name: "Aubergine" },
  { color: "#FEFDDF", name: "Barium Yellow" },
  { color: "#FFFCE9", name: "Pale Lemon" },
  { color: "#FEFEF4", name: "Yellow Fluorite" },
  { color: "#F6F396", name: "Canary Yellow" },
  { color: "#EDE556", name: "Acacia" },
  { color: "#FEF56C", name: "Yellow" },
  { color: "#FEF200", name: "Acid Yellow" },
  { color: "#FFFBCC", name: "Pale Yellow" },
  { color: "#FBF7AE", name: "Lemon Yellow" },
  { color: "#FEE96C", name: "Cadmium Yellow" },
  { color: "#FFE455", name: "Golden Yellow" },
  { color: "#FEED55", name: "Lightning Yellow" },
  { color: "#FFE93E", name: "Napoli Yellow" },
  { color: "#FFEEC2", name: "Buttercup Yellow" },
  { color: "#FBE3B3", name: "Yellowish Beige" },
  { color: "#F0DD67", name: "Mustard" },
  { color: "#CAA869", name: "Lionet Gold" },
  { color: "#F9DEC0", name: "Cashmere" },
  { color: "#FFD879", name: "Maize" },
  { color: "#FFD274", name: "Honey" },
  { color: "#E6E69E", name: "Mimosa Yellow" },
  { color: "#F2F7E0", name: "Lily White" },
  { color: "#E2EBB2", name: "Green Bice" },
  { color: "#DEEAAA", name: "Yellow Green" },
  { color: "#D6E592", name: "Salad" },
  { color: "#C4DF92", name: "Yellowish Green" },
  { color: "#A5CF4F", name: "Acid Green" },
  { color: "#82C566", name: "Lettuce Green" },
  { color: "#E5F0D0", name: "Mignonette" },
  { color: "#D4E59F", name: "Chartreuse" },
  { color: "#72C156", name: "Grass Green" },
  { color: "#F7F6BE", name: "Anise" },
  { color: "#E6EB8F", name: "New Leaf" },
  { color: "#D0E17B", name: "Celadon Green" },
  { color: "#D5EBD4", name: "Pale Cobalt Green" },
  { color: "#B4DCB7", name: "Cobalt Green" },
  { color: "#D6E9D6", name: "Pale Moss" },
  { color: "#A0CAA2", name: "Pea Green" },
  { color: "#81BF8C", name: "Moss" },
  { color: "#DAD7AE", name: "Putty" },
  { color: "#D2D29C", name: "Grayish Yellow" },
  { color: "#CBC65E", name: "Pale Olive" },
  { color: "#958F03", name: "Spanish Olive" },
  { color: "#4E6A15", name: "Marine Green" },
  { color: "#FED6BD", name: "Powder Pink" },
  { color: "#FEECD8", name: "Silk" },
  { color: "#FFF3E5", name: "Pale Chiffon" },
  { color: "#FEDAC2", name: "Peach Puff" },
  { color: "#FCDCC5", name: "Light Orange" },
  { color: "#FEC369", name: "Chrome Orange" },
  { color: "#F26F39", name: "Cadmium Orange" },
  { color: "#F15524", name: "Chinese Orange" },
  { color: "#FFE2A6", name: "Loquat" },
  { color: "#FEC84E", name: "Caramel" },
  { color: "#FBB884", name: "Pumpkin Yellow" },
  { color: "#FEB729", name: "Apricot" },
  { color: "#F26B3C", name: "Sanguine" },
  { color: "#FFE1BF", name: "Yellowish Shade" },
  { color: "#F5DDB1", name: "Cream" },
  { color: "#ECCF8B", name: "Yellow Ochre" },
  { color: "#F0CF64", name: "Pale Sepia" },
  { color: "#FEF2DA", name: "Macadamia Nut" },
  { color: "#FFDEA8", name: "Light Reddish Yellow" },
  { color: "#FDDAC4", name: "Yellowish Skin Pink" },
  { color: "#FAAE60", name: "Atoll" },
  { color: "#F37022", name: "Orange" },
  { color: "#FDC68D", name: "Mellow Peach" },
].sort(sorter);

export const Panatone = [
  { color: "#000000", name: "Black" },
  { color: "#0f0f0f", name: "Onyx" },
  { color: "#321414", name: "Seal brown" },
  { color: "#3c1414", name: "Dark sienna" },
  { color: "#592720", name: "Caput mortuum" },
  { color: "#800000", name: "Maroon" },
  { color: "#8b0000", name: "Dark red" },
  { color: "#701c1c", name: "Persian plum" },
  { color: "#801818", name: "Falu red" },
  { color: "#990000", name: "Crimson Red" },
  { color: "#a40000", name: "Dark candy apple red" },
  { color: "#555555", name: "Davy grey" },
  { color: "#674846", name: "Rose ebony" },
  { color: "#ae0c00", name: "Mordant red 19" },
  { color: "#a81c07", name: "Rufous" },
  { color: "#704241", name: "Deep coffee" },
  { color: "#645452", name: "Wenge" },
  { color: "#922724", name: "Vivid auburn" },
  { color: "#cc0000", name: "Boston University Red" },
  { color: "#b31b1b", name: "Carnelian" },
  { color: "#a52a2a", name: "Auburn" },
  { color: "#696969", name: "Dim gray" },
  { color: "#b22222", name: "Firebrick" },
  { color: "#d40000", name: "Rosso corsa" },
  { color: "#af4035", name: "Medium carmine" },
  { color: "#905d5d", name: "Rose taupe" },
  { color: "#996666", name: "Copper rose" },
  { color: "#cc3333", name: "Persian red" },
  { color: "#ff0000", name: "Red" },
  { color: "#ff0800", name: "Candy apple red" },
  { color: "#808080", name: "Gray" },
  { color: "#b94e48", name: "Deep chestnut" },
  { color: "#e62020", name: "Lust" },
  { color: "#e03c31", name: "CG Red" },
  { color: "#e34234", name: "Vermilion" },
  { color: "#cd5c5c", name: "Indian red" },
  { color: "#eb4c42", name: "Carmine pink" },
  { color: "#cc6666", name: "Fuzzy Wuzzy" },
  { color: "#ff4040", name: "Coral red" },
  { color: "#ff5349", name: "Red Orange" },
  { color: "#bc8f8f", name: "Rosy brown" },
  { color: "#fd5e53", name: "Sunset Orange" },
  { color: "#a9a9a9", name: "Dark gray" },
  { color: "#fe6f5e", name: "Bittersweet" },
  { color: "#ff6961", name: "Pastel red" },
  { color: "#f08080", name: "Light coral" },
  { color: "#f88379", name: "Coral pink" },
  { color: "#c0c0c0", name: "Silver" },
  { color: "#ff9999", name: "Light salmon pink" },
  { color: "#d3d3d3", name: "Light gray" },
  { color: "#fdbcb4", name: "Melon" },
  { color: "#f4c2c2", name: "Tea rose" },
  { color: "#dcdcdc", name: "Gainsboro" },
  { color: "#ffe4e1", name: "Misty rose" },
  { color: "#f5f5f5", name: "White smoke" },
  { color: "#fffafa", name: "Snow" },
  { color: "#ffffff", name: "White" },
  { color: "#2c1608", name: "Zinnwaldite brown" },
  { color: "#882d17", name: "Sienna" },
  { color: "#635147", name: "Umber" },
  { color: "#674c47", name: "Medium taupe" },
  { color: "#8a3324", name: "Burnt umber" },
  { color: "#79443b", name: "Bole" },
  { color: "#c04000", name: "Mahogany" },
  { color: "#b7410e", name: "Rust" },
  { color: "#cb410b", name: "Sinopia" },
  { color: "#c23b22", name: "Dark pastel red" },
  { color: "#986960", name: "Dark chestnut" },
  { color: "#f94d00", name: "Tangelo" },
  { color: "#ff2400", name: "Scarlet" },
  { color: "#ff2800", name: "Ferrari Red" },
  { color: "#ff3800", name: "Coquelicot" },
  { color: "#ff4500", name: "Orange red" },
  { color: "#ff4f00", name: "International orange" },
  { color: "#e25822", name: "Flame" },
  { color: "#9f8170", name: "Beaver" },
  { color: "#cd5b45", name: "Dark coral" },
  { color: "#98817b", name: "Cinereous" },
  { color: "#e9692c", name: "Deep carrot orange" },
  { color: "#d68a59", name: "Raw Sienna" },
  { color: "#ff5a36", name: "Portland Orange" },
  { color: "#e97451", name: "Burnt sienna" },
  { color: "#e2725b", name: "Terra cotta" },
  { color: "#da8a67", name: "Pale copper" },
  { color: "#cd9575", name: "Antique brass" },
  { color: "#ff8243", name: "Mango Tango" },
  { color: "#ff6347", name: "Tomato" },
  { color: "#ff6e4a", name: "Outrageous Orange" },
  { color: "#ff7f50", name: "Coral" },
  { color: "#e9967a", name: "Dark salmon" },
  { color: "#ff9966", name: "Atomic tangerine" },
  { color: "#deaa88", name: "Tumbleweed" },
  { color: "#ff8c69", name: "Salmon" },
  { color: "#ffa07a", name: "Light salmon" },
  { color: "#c9c0bb", name: "Pale silver" },
  { color: "#ffa089", name: "Vivid tangerine" },
  { color: "#fbceb1", name: "Apricot" },
  { color: "#100c08", name: "Smoky black" },
  { color: "#3d2b1f", name: "Bistre" },
  { color: "#4b3621", name: "Café noir" },
  { color: "#483c32", name: "Taupe" },
  { color: "#704214", name: "Sepia" },
  { color: "#654321", name: "Dark brown" },
  { color: "#80461b", name: "Russet" },
  { color: "#8b4513", name: "Saddle brown" },
  { color: "#6f4e37", name: "Coffee" },
  { color: "#996515", name: "Golden brown" },
  { color: "#b06500", name: "Ginger" },
  { color: "#cc5500", name: "Burnt orange" },
  { color: "#cd5700", name: "Tawny" },
  { color: "#b5651d", name: "Light brown" },
  { color: "#836953", name: "Pastel brown" },
  { color: "#da9100", name: "Harvest Gold" },
  { color: "#bb6528", name: "Ruddy brown" },
  { color: "#e48400", name: "Fulvous" },
  { color: "#8a795d", name: "Shadow" },
  { color: "#b87333", name: "Copper" },
  { color: "#987654", name: "Pale brown" },
  { color: "#cc7722", name: "Ochre" },
  { color: "#d2691e", name: "Chocolate" },
  { color: "#f28500", name: "Tangerine" },
  { color: "#e49b0f", name: "Gamboge" },
  { color: "#a0785a", name: "Chamoisee" },
  { color: "#cd7f32", name: "Bronze" },
  { color: "#ff6700", name: "Safety orange" },
  { color: "#ff8c00", name: "Dark orange" },
  { color: "#ff8f00", name: "Princeton orange" },
  { color: "#ff9f00", name: "Orange peel" },
  { color: "#ffa500", name: "Orange" },
  { color: "#ffa700", name: "Chrome yellow" },
  { color: "#a67b5b", name: "French beige" },
  { color: "#ed9121", name: "Carrot orange" },
  { color: "#ffa812", name: "Dark tangerine" },
  { color: "#ff7518", name: "Pumpkin" },
  { color: "#ed872d", name: "Cadmium orange" },
  { color: "#e08d3c", name: "Tiger eye" },
  { color: "#b38b6d", name: "Light taupe" },
  { color: "#c19a6b", name: "Desert" },
  { color: "#a99a86", name: "Grullo" },
  { color: "#d99058", name: "Persian orange" },
  { color: "#ff9933", name: "Deep saffron" },
  { color: "#bc987e", name: "Pale taupe" },
  { color: "#e3a857", name: "Indian yellow" },
  { color: "#e1a95f", name: "Earth yellow" },
  { color: "#ffae42", name: "Yellow Orange" },
  { color: "#ffa343", name: "Neon Carrot" },
  { color: "#ffb347", name: "Pastel orange" },
  { color: "#c3b091", name: "Khaki" },
  { color: "#f4a460", name: "Sandy brown" },
  { color: "#e5aa70", name: "Fawn" },
  { color: "#d2b48c", name: "Tan" },
  { color: "#deb887", name: "Burlywood" },
  { color: "#e6be8a", name: "Pale gold" },
  { color: "#ffc87c", name: "Topaz" },
  { color: "#ffbd88", name: "Macaroni and Cheese" },
  { color: "#edc9af", name: "Desert sand" },
  { color: "#fad6a5", name: "Champagne" },
  { color: "#ffcba4", name: "Deep peach" },
  { color: "#fadfad", name: "Peach yellow" },
  { color: "#f5deb3", name: "Wheat" },
  { color: "#e3dac9", name: "Bone" },
  { color: "#ffdead", name: "Navajo white" },
  { color: "#dbd7d2", name: "Timberwolf" },
  { color: "#fdd5b1", name: "Light apricot" },
  { color: "#ffe5b4", name: "Peach" },
  { color: "#ffdab9", name: "Peach puff" },
  { color: "#efdecd", name: "Almond" },
  { color: "#ffe4c4", name: "Bisque" },
  { color: "#ffebcd", name: "Blanched Almond" },
  { color: "#faebd7", name: "Antique white" },
  { color: "#ffefd5", name: "Papaya whip" },
  { color: "#f4f0ec", name: "Isabelline" },
  { color: "#faf0e6", name: "Linen" },
  { color: "#fdf5e6", name: "Old lace" },
  { color: "#fff5ee", name: "Seashell" },
  { color: "#6c541e", name: "Field drab" },
  { color: "#967117", name: "Sandy taupe" },
  { color: "#b8860b", name: "Dark goldenrod" },
  { color: "#b78727", name: "University of California Gold" },
  { color: "#918151", name: "Dark tan" },
  { color: "#e4d00a", name: "Citrine" },
  { color: "#b5a642", name: "Brass" },
  { color: "#daa520", name: "Goldenrod" },
  { color: "#fcc200", name: "Golden poppy" },
  { color: "#ffb300", name: "UCLA Gold" },
  { color: "#ffba00", name: "Selective yellow" },
  { color: "#ffbf00", name: "Amber" },
  { color: "#ffcc00", name: "Tangerine yellow" },
  { color: "#ffd700", name: "Gold" },
  { color: "#ffd800", name: "School bus yellow" },
  { color: "#ffdf00", name: "Golden yellow" },
  { color: "#cba135", name: "Satin sheen gold" },
  { color: "#e1ad21", name: "Urobilin" },
  { color: "#cfb53b", name: "Old gold" },
  { color: "#ffc40c", name: "Mikado yellow" },
  { color: "#c5b358", name: "Vegas gold" },
  { color: "#e5b73b", name: "Meat brown" },
  { color: "#f0e130", name: "Dandelion" },
  { color: "#f4c430", name: "Saffron" },
  { color: "#bdb76b", name: "Dark khaki" },
  { color: "#ecd540", name: "Sandstorm" },
  { color: "#ffcc33", name: "Sunglow" },
  { color: "#ffe135", name: "Banana yellow" },
  { color: "#c2b280", name: "Ecru" },
  { color: "#e4d96f", name: "Straw" },
  { color: "#e9d66b", name: "Hansa yellow" },
  { color: "#ffdb58", name: "Mustard" },
  { color: "#fada5e", name: "Naples yellow" },
  { color: "#fbec5d", name: "Corn" },
  { color: "#f8d568", name: "Orange Yellow" },
  { color: "#eedc82", name: "Flax" },
  { color: "#f0dc82", name: "Buff" },
  { color: "#f8de7e", name: "Jasmine" },
  { color: "#f0e68c", name: "Light khaki" },
  { color: "#f7e98e", name: "Flavescent" },
  { color: "#eee8aa", name: "Pale goldenrod" },
  { color: "#f3e5ab", name: "Vanilla" },
  { color: "#fae7b5", name: "Banana Mania" },
  { color: "#eae0c8", name: "Pearl" },
  { color: "#faf0be", name: "Blond" },
  { color: "#f0ead6", name: "Eggshell" },
  { color: "#e5e4e2", name: "Platinum" },
  { color: "#fffacd", name: "Lemon chiffon" },
  { color: "#fff8dc", name: "Cornsilk" },
  { color: "#fff8e7", name: "Cosmic latte" },
  { color: "#fffaf0", name: "Floral white" },
  { color: "#4b5320", name: "Army green" },
  { color: "#808000", name: "Olive" },
  { color: "#e6e200", name: "Peridot" },
  { color: "#eee600", name: "Titanium yellow" },
  { color: "#fdee00", name: "Aureolin" },
  { color: "#ffef00", name: "Canary yellow" },
  { color: "#fff600", name: "Cadmium yellow" },
  { color: "#fff700", name: "Lemon" },
  { color: "#ffff00", name: "Yellow" },
  { color: "#848482", name: "Battleship grey" },
  { color: "#d1e231", name: "Pear" },
  { color: "#fefe22", name: "Laser Lemon" },
  { color: "#bab86c", name: "Olive Green" },
  { color: "#ffff31", name: "Daffodil" },
  { color: "#fff44f", name: "Lemon Yellow" },
  { color: "#fcf75e", name: "Icterine" },
  { color: "#ffff66", name: "Unmellow Yellow" },
  { color: "#cfcfc4", name: "Pastel gray" },
  { color: "#fdfd96", name: "Pastel yellow" },
  { color: "#ffff99", name: "Canary" },
  { color: "#ecebbd", name: "Pale spring bud" },
  { color: "#fafad2", name: "Light goldenrod yellow" },
  { color: "#fffdd0", name: "Cream" },
  { color: "#f5f5dc", name: "Beige" },
  { color: "#ffffed", name: "Light yellow" },
  { color: "#fffff0", name: "Ivory" },
  { color: "#414833", name: "Rifle green" },
  { color: "#556b2f", name: "Dark olive green" },
  { color: "#6b8e23", name: "Olive Drab" },
  { color: "#8db600", name: "Apple green" },
  { color: "#a7fc00", name: "Spring bud" },
  { color: "#a4c639", name: "Android Green" },
  { color: "#9acd32", name: "Yellow green" },
  { color: "#ccff00", name: "Fluorescent yellow" },
  { color: "#bfff00", name: "Lime" },
  { color: "#9ab973", name: "Olivine" },
  { color: "#adff2f", name: "Green yellow" },
  { color: "#bdda57", name: "June bud" },
  { color: "#b2ec5d", name: "Inchworm" },
  { color: "#c9dc87", name: "Medium spring bud" },
  { color: "#2a8000", name: "Napier green" },
  { color: "#507d2a", name: "Sap green" },
  { color: "#4cbb17", name: "Kelly green" },
  { color: "#78866b", name: "Camouflage green" },
  { color: "#7cfc00", name: "Lawn green" },
  { color: "#66ff00", name: "Bright green" },
  { color: "#7fff00", name: "Chartreuse" },
  { color: "#87a96b", name: "Asparagus" },
  { color: "#85bb65", name: "Dollar bill" },
  { color: "#93c572", name: "Pistachio" },
  { color: "#a9ba9d", name: "Laurel green" },
  { color: "#d0f0c0", name: "Tea green" },
  { color: "#195905", name: "Lincoln green" },
  { color: "#21421e", name: "Myrtle" },
  { color: "#138808", name: "India green" },
  { color: "#465945", name: "Gray asparagus" },
  { color: "#4f7942", name: "Fern green" },
  { color: "#3fff00", name: "Harlequin" },
  { color: "#39ff14", name: "Neon green" },
  { color: "#74c365", name: "Mantis" },
  { color: "#a8e4a0", name: "Granny Smith Apple" },
  { color: "#006600", name: "Pakistan green" },
  { color: "#008000", name: "Office green" },
  { color: "#009000", name: "Islamic green" },
  { color: "#355e3b", name: "Hunter green" },
  { color: "#228b22", name: "Forest green" },
  { color: "#738678", name: "Xanadu" },
  { color: "#32cd32", name: "Lime green" },
  { color: "#00ff00", name: "Green" },
  { color: "#71bc78", name: "Fern" },
  { color: "#8fbc8f", name: "Dark sea green" },
  { color: "#77dd77", name: "Pastel green" },
  { color: "#96c8a2", name: "Eton blue" },
  { color: "#b2beb5", name: "Ash grey" },
  { color: "#76ff7a", name: "Screamin Green" },
  { color: "#90ee90", name: "Light green" },
  { color: "#addfad", name: "Moss green" },
  { color: "#ace1af", name: "Celadon" },
  { color: "#98fb98", name: "Pale green" },
  { color: "#98ff98", name: "Mint green" },
  { color: "#f0fff0", name: "Honeydew" },
  { color: "#014421", name: "UP Forest green" },
  { color: "#123524", name: "Phthalo green" },
  { color: "#1e4d2b", name: "Cal Poly Pomona green" },
  { color: "#087830", name: "La Salle Green" },
  { color: "#177245", name: "Dark spring green" },
  { color: "#059033", name: "North Texas Green" },
  { color: "#4d5d53", name: "Feldgrau" },
  { color: "#2e8b57", name: "Sea green" },
  { color: "#03c03c", name: "Dark pastel green" },
  { color: "#0bda51", name: "Malachite" },
  { color: "#3cb371", name: "Medium sea green" },
  { color: "#00ff7f", name: "Spring green" },
  { color: "#3cd070", name: "UFO Green" },
  { color: "#50c878", name: "Emerald" },
  { color: "#a3c1ad", name: "Cambridge Blue" },
  { color: "#a0d6b4", name: "Turquoise green" },
  { color: "#f5fffa", name: "Mint cream" },
  { color: "#013220", name: "Dark green" },
  { color: "#1a2421", name: "Dark jungle green" },
  { color: "#004225", name: "British racing green" },
  { color: "#1c352d", name: "Medium jungle green" },
  { color: "#00563f", name: "Sacramento State green" },
  { color: "#18453b", name: "MSU Green" },
  { color: "#00693e", name: "Dartmouth green" },
  { color: "#006a4e", name: "Bottle green" },
  { color: "#006b3c", name: "Cadmium green" },
  { color: "#009e60", name: "Shamrock green" },
  { color: "#00a86b", name: "Jade" },
  { color: "#49796b", name: "Hooker green" },
  { color: "#40826d", name: "Viridian" },
  { color: "#00cc99", name: "Caribbean green" },
  { color: "#29ab87", name: "Jungle green" },
  { color: "#30ba8f", name: "Mountain Meadow" },
  { color: "#3eb489", name: "Mint" },
  { color: "#00fa9a", name: "Medium spring green" },
  { color: "#45cea2", name: "Shamrock" },
  { color: "#66ddaa", name: "Medium aquamarine" },
  { color: "#88d8c0", name: "Pearl Aqua" },
  { color: "#7fffd4", name: "Aquamarine" },
  { color: "#aaf0d1", name: "Magic mint" },
  { color: "#004040", name: "Rich black" },
  { color: "#004242", name: "Warm black" },
  { color: "#004b49", name: "Deep jungle green" },
  { color: "#006d5b", name: "Teal green" },
  { color: "#007474", name: "Skobeloff" },
  { color: "#00755e", name: "Tropical rain forest" },
  { color: "#01796f", name: "Pine green" },
  { color: "#2f4f4f", name: "Dark slate gray" },
  { color: "#008080", name: "Teal" },
  { color: "#008b8b", name: "Dark cyan" },
  { color: "#0abab5", name: "Tiffany Blue" },
  { color: "#00ced1", name: "Dark turquoise" },
  { color: "#20b2aa", name: "Light sea green" },
  { color: "#1fcecb", name: "Robin's Egg Blue" },
  { color: "#6e7f80", name: "AuroMetalSaurus" },
  { color: "#08e8de", name: "Bright turquoise" },
  { color: "#43b3ae", name: "Verdigris" },
  { color: "#5f9ea0", name: "Cadet blue" },
  { color: "#00ffef", name: "Turquoise blue" },
  { color: "#00ffff", name: "Cyan" },
  { color: "#30d5c8", name: "Turquoise" },
  { color: "#48d1cc", name: "Medium turquoise" },
  { color: "#96ded1", name: "Pale robin egg blue" },
  { color: "#7df9ff", name: "Electric blue" },
  { color: "#afeeee", name: "Pale blue" },
  { color: "#b2ffff", name: "Celeste" },
  { color: "#e0ffff", name: "Light cyan" },
  { color: "#e7feff", name: "Bubbles" },
  { color: "#f0ffff", name: "Azure mist/web" },
  { color: "#004953", name: "Midnight green" },
  { color: "#414a4c", name: "Outer Space" },
  { color: "#006994", name: "Sea blue" },
  { color: "#007aa5", name: "CG Blue" },
  { color: "#007ba7", name: "Cerulean" },
  { color: "#0095b6", name: "Bondi blue" },
  { color: "#367588", name: "Teal blue" },
  { color: "#536872", name: "Cadet" },
  { color: "#0d98ba", name: "Blue green" },
  { color: "#0892d0", name: "Rich electric blue" },
  { color: "#1ca9c9", name: "Pacific Blue" },
  { color: "#21abcd", name: "Ball Blue" },
  { color: "#1dacd6", name: "Bright cerulean" },
  { color: "#00bfff", name: "Deep sky blue" },
  { color: "#0fc0fc", name: "Spiro Disco Ball" },
  { color: "#73a9c2", name: "Moonstone blue" },
  { color: "#87ceeb", name: "Sky blue" },
  { color: "#89cff0", name: "Baby blue" },
  { color: "#aec6cf", name: "Pastel blue" },
  { color: "#a4dded", name: "Non-photo blue" },
  { color: "#add8e6", name: "Light blue" },
  { color: "#b0e0e6", name: "Powder blue" },
  { color: "#ace5ee", name: "Blizzard Blue" },
  { color: "#002147", name: "Oxford Blue" },
  { color: "#003153", name: "Prussian blue" },
  { color: "#002e63", name: "Cool black" },
  { color: "#003366", name: "Dark midnight blue" },
  { color: "#36454f", name: "Charcoal" },
  { color: "#08457e", name: "Dark cerulean" },
  { color: "#035096", name: "Medium electric blue" },
  { color: "#0f4d92", name: "Yale Blue" },
  { color: "#0067a5", name: "Medium Persian blue" },
  { color: "#0047ab", name: "Cobalt" },
  { color: "#0054b4", name: "Medium teal blue" },
  { color: "#0072bb", name: "French blue" },
  { color: "#0077be", name: "Ocean Boat Blue" },
  { color: "#26619c", name: "Lapis lazuli" },
  { color: "#1164b4", name: "Green Blue" },
  { color: "#536878", name: "Dark electric blue" },
  { color: "#0073cf", name: "True Blue" },
  { color: "#1560bd", name: "Denim" },
  { color: "#4682b4", name: "Steel blue" },
  { color: "#0070ff", name: "Brandeis blue" },
  { color: "#007fff", name: "Azure" },
  { color: "#708090", name: "Slate gray" },
  { color: "#417dc1", name: "Tufts Blue" },
  { color: "#5d8aa8", name: "Air Force blue" },
  { color: "#778899", name: "Light slate gray" },
  { color: "#318ce7", name: "Bleu de France" },
  { color: "#4997d0", name: "Celestial blue" },
  { color: "#1e90ff", name: "Dodger blue" },
  { color: "#6699cc", name: "Blue Gray" },
  { color: "#91a3b0", name: "Cadet grey" },
  { color: "#779ecb", name: "Dark pastel blue" },
  { color: "#73c2fb", name: "Maya blue" },
  { color: "#99badd", name: "Carolina blue" },
  { color: "#9bc4e2", name: "Pale cerulean" },
  { color: "#93ccea", name: "Light cornflower blue" },
  { color: "#87cefa", name: "Light sky blue" },
  { color: "#9aceeb", name: "Cornflower" },
  { color: "#a1caf1", name: "Baby blue eyes" },
  { color: "#abcdef", name: "Pale cornflower blue" },
  { color: "#9bddff", name: "Columbia blue" },
  { color: "#bcd4e6", name: "Pale aqua" },
  { color: "#f2f3f4", name: "Munsell" },
  { color: "#f0f8ff", name: "Alice blue" },
  { color: "#003399", name: "Dark powder blue" },
  { color: "#002fa7", name: "International Klein Blue" },
  { color: "#0038a8", name: "Royal azure" },
  { color: "#0033aa", name: "UA blue" },
  { color: "#1034a6", name: "Egyptian blue" },
  { color: "#0f52ba", name: "Sapphire" },
  { color: "#1c39bb", name: "Persian blue" },
  { color: "#324ab2", name: "Violet Blue" },
  { color: "#536895", name: "UCLA Blue" },
  { color: "#2a52be", name: "Cerulean blue" },
  { color: "#446ccf", name: "Han blue" },
  { color: "#6082b6", name: "Glaucous" },
  { color: "#4169e1", name: "Royal blue" },
  { color: "#4166f5", name: "Ultramarine blue" },
  { color: "#8c92ac", name: "Cool grey" },
  { color: "#5b92e5", name: "United Nations blue" },
  { color: "#979aaa", name: "Manatee" },
  { color: "#6495ed", name: "Cornflower blue" },
  { color: "#a2add0", name: "Wild blue yonder" },
  { color: "#000080", name: "Navy blue" },
  { color: "#191970", name: "Midnight blue" },
  { color: "#000f89", name: "Phthalo blue" },
  { color: "#00008b", name: "Dark blue" },
  { color: "#120a8f", name: "Ultramarine" },
  { color: "#00009c", name: "Duke blue" },
  { color: "#23297a", name: "Saint Patrick Blue" },
  { color: "#0014a8", name: "Zaffre" },
  { color: "#0000cd", name: "Medium blue" },
  { color: "#0000ff", name: "Blue" },
  { color: "#273be2", name: "Palatinate blue" },
  { color: "#5a4fcf", name: "Iris" },
  { color: "#746cc0", name: "Toolbox" },
  { color: "#6050dc", name: "Majorelle Blue" },
  { color: "#a2a2d0", name: "Blue Bell" },
  { color: "#c4c3d0", name: "Lavender gray" },
  { color: "#ccccff", name: "Periwinkle" },
  { color: "#e6e8fa", name: "Glitter" },
  { color: "#e6e6fa", name: "Lavender" },
  { color: "#f8f8ff", name: "Ghost white" },
  { color: "#32127a", name: "Persian indigo" },
  { color: "#483d8b", name: "Dark slate blue" },
  { color: "#3f00ff", name: "Electric ultramarine" },
  { color: "#5218fa", name: "Han purple" },
  { color: "#6a5acd", name: "Slate blue" },
  { color: "#8878c3", name: "Ube" },
  { color: "#966fd6", name: "Dark pastel purple" },
  { color: "#9370db", name: "Medium purple" },
  { color: "#7b68ee", name: "Medium slate blue" },
  { color: "#b19cd9", name: "Light pastel purple" },
  { color: "#dcd0ff", name: "Pale lavender" },
  { color: "#f8f4ff", name: "Magnolia" },
  { color: "#4b0082", name: "Indigo" },
  { color: "#69359c", name: "Purple Heart" },
  { color: "#734f96", name: "Dark lavender" },
  { color: "#7851a9", name: "Royal purple" },
  { color: "#6f00ff", name: "Electric indigo" },
  { color: "#8f00ff", name: "Electric violet" },
  { color: "#9f00ff", name: "Vivid violet" },
  { color: "#8a2be2", name: "Blue violet" },
  { color: "#a020f0", name: "Veronica" },
  { color: "#9678b6", name: "Purple mountain majesty" },
  { color: "#967bb6", name: "Lavender purple" },
  { color: "#9966cc", name: "Amethyst" },
  { color: "#9d81ba", name: "Purple Mountain's Majesty" },
  { color: "#9457eb", name: "Lavender indigo" },
  { color: "#bf94e4", name: "Bright lavender" },
  { color: "#d6cadd", name: "Languid lavender" },
  { color: "#e0b0ff", name: "Mauve" },
  { color: "#9400d3", name: "Dark violet" },
  { color: "#86608e", name: "French lilac" },
  { color: "#9932cc", name: "Dark orchid" },
  { color: "#bf00ff", name: "Electric purple" },
  { color: "#9955bb", name: "Deep lilac" },
  { color: "#ba55d3", name: "Medium orchid" },
  { color: "#b666d2", name: "Rich lilac" },
  { color: "#b39eb5", name: "Pastel purple" },
  { color: "#df73ff", name: "Heliotrope" },
  { color: "#c9a0dc", name: "Wisteria" },
  { color: "#d19fe8", name: "Bright ube" },
  { color: "#f4bbff", name: "Brilliant lavender" },
  { color: "#800080", name: "Purple" },
  { color: "#8b008b", name: "Dark magenta" },
  { color: "#50404d", name: "Purple taupe" },
  { color: "#682860", name: "Palatinate purple" },
  { color: "#702963", name: "Byzantium" },
  { color: "#cc00cc", name: "Deep magenta" },
  { color: "#796878", name: "Old lavender" },
  { color: "#bd33a4", name: "Byzantine" },
  { color: "#ff00ff", name: "Fuchsia" },
  { color: "#c154c1", name: "Deep fuchsia" },
  { color: "#aa98a9", name: "Rose quartz" },
  { color: "#da70d6", name: "Orchid" },
  { color: "#cb99c9", name: "Pastel violet" },
  { color: "#c8a2c8", name: "Lilac" },
  { color: "#ff6fff", name: "Ultra pink" },
  { color: "#ee82ee", name: "Violet" },
  { color: "#fc74fd", name: "Pink Flamingo" },
  { color: "#ff77ff", name: "Fuchsia pink" },
  { color: "#dda0dd", name: "Plum" },
  { color: "#f984ef", name: "Light fuchsia pink" },
  { color: "#f984e5", name: "Pale magenta" },
  { color: "#d8bfd8", name: "Thistle" },
  { color: "#66023c", name: "Tyrian purple" },
  { color: "#5d3954", name: "Dark byzantium" },
  { color: "#663854", name: "Halayà úbe" },
  { color: "#a50b5e", name: "Jazzberry jam" },
  { color: "#873260", name: "Boysenberry" },
  { color: "#c71585", name: "Red violet" },
  { color: "#b53389", name: "Fandango" },
  { color: "#915c83", name: "Antique fuchsia" },
  { color: "#bb3385", name: "Medium red violet" },
  { color: "#f400a1", name: "Fashion fuchsia" },
  { color: "#ca2c92", name: "Royal fuchsia" },
  { color: "#fc0fc0", name: "Shocking pink" },
  { color: "#8b8589", name: "Taupe gray" },
  { color: "#997a8d", name: "Mountbatten pink" },
  { color: "#ff1493", name: "Deep pink" },
  { color: "#ff1dce", name: "Hot magenta" },
  { color: "#fe28a2", name: "Persian rose" },
  { color: "#ff33cc", name: "Razzle dazzle rose" },
  { color: "#b784a7", name: "Opera mauve" },
  { color: "#cf71af", name: "Sky magenta" },
  { color: "#fe4eda", name: "Purple pizzazz" },
  { color: "#fe59c2", name: "Neon fuchsia" },
  { color: "#ff66cc", name: "Rose pink" },
  { color: "#e7accf", name: "Pink pearl" },
  { color: "#fba0e3", name: "Lavender rose" },
  { color: "#fbcce7", name: "Classic rose" },
  { color: "#78184a", name: "Pansy purple" },
  { color: "#673147", name: "Old mauve" },
  { color: "#534b4f", name: "Liver" },
  { color: "#614051", name: "Eggplant" },
  { color: "#66424d", name: "Tuscan red" },
  { color: "#872657", name: "Dark raspberry" },
  { color: "#8a496b", name: "Twilight lavender" },
  { color: "#d3003f", name: "Utah Crimson" },
  { color: "#d70040", name: "Rich carmine" },
  { color: "#d9004c", name: "UA red" },
  { color: "#b03060", name: "Rich maroon" },
  { color: "#d70a53", name: "Debian red" },
  { color: "#e30b5d", name: "Raspberry" },
  { color: "#d71868", name: "Dogwood rose" },
  { color: "#915f6d", name: "Mauve taupe" },
  { color: "#e0115f", name: "Ruby" },
  { color: "#b3446c", name: "Raspberry rose" },
  { color: "#da1d81", name: "Vivid cerise" },
  { color: "#ff004f", name: "Folly" },
  { color: "#ff007f", name: "Rose" },
  { color: "#e3256b", name: "Razzmatazz" },
  { color: "#da3287", name: "Deep cerise" },
  { color: "#de3163", name: "Cherry" },
  { color: "#c54b8c", name: "Mulberry" },
  { color: "#ec3b83", name: "Cerise pink" },
  { color: "#e25098", name: "Raspberry pink" },
  { color: "#de5d83", name: "Blush" },
  { color: "#e75480", name: "Dark pink" },
  { color: "#f9429e", name: "Rose bonbon" },
  { color: "#f64a8a", name: "French rose" },
  { color: "#ff43a4", name: "Wild Strawberry" },
  { color: "#f75394", name: "Violet Red" },
  { color: "#db7093", name: "Pale violet red" },
  { color: "#de6fa1", name: "Thulian pink" },
  { color: "#ff55a3", name: "Brilliant rose" },
  { color: "#f56991", name: "Light Crimson" },
  { color: "#ff69b4", name: "Hot pink" },
  { color: "#e68fac", name: "Light Thulian pink" },
  { color: "#f77fbe", name: "Persian pink" },
  { color: "#fc89ac", name: "Tickle Me Pink" },
  { color: "#fc8eac", name: "Flamingo pink" },
  { color: "#f49ac2", name: "Pastel magenta" },
  { color: "#f6adc6", name: "Nadeshiko pink" },
  { color: "#ffa6c9", name: "Carnation pink" },
  { color: "#fbaed2", name: "Lavender pink" },
  { color: "#ffbcd9", name: "Cotton candy" },
  { color: "#fddde6", name: "Piggy pink" },
  { color: "#fff0f5", name: "Lavender blush" },
  { color: "#480607", name: "Bulgarian rose" },
  { color: "#560319", name: "Dark scarlet" },
  { color: "#65000b", name: "Rosewood" },
  { color: "#800020", name: "Burgundy" },
  { color: "#7b1113", name: "UP Maroon" },
  { color: "#722f37", name: "Wine" },
  { color: "#9f1d35", name: "Vivid burgundy" },
  { color: "#be0032", name: "Crimson glory" },
  { color: "#893f45", name: "Cordovan" },
  { color: "#a9203e", name: "Deep carmine" },
  { color: "#c90016", name: "Harvard crimson" },
  { color: "#ae2029", name: "Upsdell red" },
  { color: "#933d41", name: "Smokey topaz" },
  { color: "#c80815", name: "Venetian red" },
  { color: "#cf1020", name: "Lava" },
  { color: "#c41e3a", name: "Cardinal" },
  { color: "#e30022", name: "Cadmium red" },
  { color: "#c32148", name: "Bright maroon" },
  { color: "#e2062c", name: "Medium candy apple red" },
  { color: "#e8000d", name: "KU Crimson" },
  { color: "#ce2029", name: "Fire engine red" },
  { color: "#dc143c", name: "Crimson" },
  { color: "#ab4e52", name: "Rose vale" },
  { color: "#ff0040", name: "Carmine" },
  { color: "#ff003f", name: "Electric crimson" },
  { color: "#ff0038", name: "Carmine red" },
  { color: "#ff0028", name: "Ruddy" },
  { color: "#ff033e", name: "American rose" },
  { color: "#e32636", name: "Rose madder" },
  { color: "#fd0e35", name: "Tractor red" },
  { color: "#cb4154", name: "Brick red" },
  { color: "#98777b", name: "Bazaar" },
  { color: "#e52b50", name: "Amaranth" },
  { color: "#d73b3e", name: "Jasper" },
  { color: "#cc4e5c", name: "Dark terra cotta" },
  { color: "#ef3038", name: "Deep carmine pink" },
  { color: "#ff2052", name: "Awesome" },
  { color: "#b76e79", name: "Rose gold" },
  { color: "#b57281", name: "Turkish rose" },
  { color: "#ff355e", name: "Radical Red" },
  { color: "#c08081", name: "Old rose" },
  { color: "#e66771", name: "Light carmine pink" },
  { color: "#cc8899", name: "Puce" },
  { color: "#e4717a", name: "Candy pink" },
  { color: "#fb607f", name: "Brink pink" },
  { color: "#fc6c85", name: "Wild Watermelon" },
  { color: "#e18e96", name: "Ruddy pink" },
  { color: "#f78fa7", name: "Pink Sherbet" },
  { color: "#ef98aa", name: "Mauvelous" },
  { color: "#ddadaf", name: "Pale chestnut" },
  { color: "#ff91a4", name: "Salmon pink" },
  { color: "#ffb6c1", name: "Light pink" },
  { color: "#ffb7c5", name: "Cherry blossom pink" },
  { color: "#ffc0cb", name: "Pink" },
  { color: "#ffc1cc", name: "Bubble gum" },
  { color: "#ffd1dc", name: "Pastel pink" },
  { color: "#fadadd", name: "Pale pink" },
].sort(sorter);
